In [1]:
import pandas as pd
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [2]:
cr = pd.read_csv(r"D:Downloads/Datasets/CreditRisk.csv") #used tp read a external file.

In [3]:
cr.shape

(981, 13)

In [4]:
cr.head() #this will show me the top 5 records in my file

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [5]:
cr.tail() # this will show me the last 5 records in my file

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
976,LP002971,Male,Yes,4.0,Not Graduate,Yes,4009,1777.0,113.0,360.0,1.0,Urban,Y
977,LP002975,Male,Yes,0.0,Graduate,No,4158,709.0,115.0,360.0,1.0,Urban,Y
978,LP002980,Male,No,0.0,Graduate,No,3250,1993.0,126.0,360.0,NaN,Semiurban,Y
979,LP002986,Male,Yes,0.0,Graduate,No,5000,2393.0,158.0,360.0,1.0,Rural,N
980,LP002989,Male,No,0.0,Graduate,Yes,9200,0.0,98.0,180.0,1.0,Rural,Y

In [6]:
cr.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [7]:
cr.Gender

0        Male
1        Male
2        Male
3        Male
4        Male
5        Male
6        Male
7        Male
8        Male
9        Male
10       Male
11       Male
12       Male
13       Male
14       Male
15       Male
16       Male
17     Female
18       Male
19       Male
20       Male
21       Male
22       Male
23        NaN
24       Male
25       Male
26       Male
27       Male
28       Male
29     Female
30       Male
31       Male
32       Male
33       Male
34       Male
35       Male
36       Male
37     Female
38       Male
39       Male
40       Male
41       Male
42       Male
43       Male
44       Male
45     Female
46       Male
47       Male
48     Female
49     Female
50     Female
51     Female
52     Female
53       Male
54     Female
55       Male
56       Male
57       Male
58       Male
59       Male
60       Male
61       Male
62       Male
63       Male
64     Female
65       Male
66       Male
67       Male
68       Male
69     Female
70       Male
71       Male
72       Male
73       Male
74       Male
75       Male
76       Male
77       Male
78       Male
79       Male
80     Female
81       Male
82     Female
83       Male
84       Male
85       Male
86       Male
87       Male
88       Male
89       Male
90       Male
91       Male
92       Male
93       Male
94       Male
95       Male
96     Female
97       Male
98       Male
99       Male
100      Male
101      Male
102      Male
103      Male
104      Male
105      Male
106      Male
107      Male
108      Male
109      Male
110      Male
111    Female
112      Male
113    Female
114      Male
115      Male
116    Female
117      Male
118      Male
119    Female
120      Male
121    Female
122    Female
123      Male
124      Male
125    Female
126       NaN
127      Male
128      Male
129      Male
130      Male
131      Male
132      Male
133      Male
134      Male
135      Male
136    Female
137      Male
138      Male
139      Male
140      Male
141      Male
142      Male
143      Male
144      Male
145    Female
146    Female
147      Male
148    Female
149      Male
150      Male
151      Male
152      Male
153      Male
154      Male
155      Male
156      Male
157      Male
158      Male
159      Male
160      Male
161      Male
162      Male
163      Male
164      Male
165      Male
166    Female
167      Male
168      Male
169      Male
170      Male
171       NaN
172      Male
173      Male
174      Male
175      Male
176      Male
177      Male
178      Male
179      Male
180      Male
181      Male
182      Male
183      Male
184    Female
185      Male
186      Male
187      Male
188       NaN
189      Male
190      Male
191      Male
192      Male
193      Male
194      Male
195      Male
196      Male
197    Female
198    Female
199      Male
200      Male
201      Male
202      Male
203      Male
204      Male
205    Female
206    Female
207      Male
208      Male
209      Male
210    Female
211      Male
212      Male
213      Male
214      Male
215      Male
216      Male
217      Male
218      Male
219    Female
220      Male
221      Male
222      Male
223      Male
224      Male
225      Male
226      Male
227      Male
228      Male
229      Male
230      Male
231      Male
232      Male
233    Female
234      Male
235      Male
236      Male
237    Female
238    Female
239      Male
240      Male
241      Male
242      Male
243      Male
244      Male
245      Male
246      Male
247      Male
248      Male
249      Male
250      Male
251    Female
252      Male
253      Male
254      Male
255    Female
256      Male
257      Male
258      Male
259      Male
260      Male
261      Male
262    Female
263    Female
264      Male
265      Male
266      Male
267      Male
268    Female
269    Female
270    Female
271      Male
272      Male
273      Male
274      Male
275      Male
276      Male
277      Male
278      Male
279    Female
280      Male
281      Male
282      Male
283    Female
284      Male
285      Male
286    Female
287      Male
288    Female
289      Male
290      Male
291      Male
292      Male
293    Female
294      Male
295      Male
296      Male
297    Female
298    Female
299      Male
300      Male
301      Male
302    Female
303      Male
304      Male
305      Male
306    Female
307    Female
308      Male
309      Male
310    Female
311      Male
312    Female
313      Male
314       NaN
315      Male
316      Male
317      Male
318    Female
319      Male
320      Male
321      Male
322      Male
323    Female
324      Male
325      Male
326      Male
327      Male
328    Female
329    Female
330      Male
331      Male
332      Male
333      Male
334       NaN
335      Male
336      Male
337      Male
338    Female
339    Female
340      Male
341    Female
342      Male
343      Male
344      Male
345      Male
346      Male
347      Male
348      Male
349      Male
350      Male
351      Male
352      Male
353    Female
354    Female
355    Female
356      Male
357      Male
358      Male
359      Male
360    Female
361      Male
362      Male
363      Male
364      Male
365      Male
366      Male
367      Male
368      Male
369      Male
370    Female
371      Male
372      Male
373      Male
374    Female
375      Male
376      Male
377      Male
378      Male
379      Male
380      Male
381      Male
382    Female
383      Male
384      Male
385      Male
386      Male
387      Male
388      Male
389      Male
390      Male
391      Male
392      Male
393      Male
394      Male
395      Male
396    Female
397      Male
398      Male
399    Female
400      Male
401      Male
402      Male
403    Female
404    Female
405    Female
406      Male
407    Female
408      Male
409      Male
410    Female
411      Male
412      Male
413      Male
414    Female
415    Female
416    Female
417      Male
418      Male
419      Male
420      Male
421    Female
422      Male
423      Male
424      Male
425      Male
426    Female
427      Male
428      Male
429      Male
430    Female
431      Male
432      Male
433      Male
434      Male
435    Female
436      Male
437      Male
438      Male
439    Female
440      Male
441      Male
442      Male
443      Male
444      Male
445      Male
446      Male
447      Male
448      Male
449      Male
450      Male
451      Male
452      Male
453      Male
454      Male
455      Male
456      Male
457      Male
458      Male
459      Male
460       NaN
461      Male
462      Male
463    Female
464      Male
465      Male
466      Male
467       NaN
468    Female
469      Male
470      Male
471      Male
472      Male
473    Female
474      Male
475      Male
476      Male
477       NaN
478      Male
479      Male
480    Female
481      Male
482      Male
483      Male
484      Male
485      Male
486      Male
487      Male
488      Male
489      Male
490      Male
491      Male
492      Male
493    Female
494      Male
495    Female
496      Male
497      Male
498      Male
499      Male
500    Female
501    Female
502      Male
503      Male
504      Male
505      Male
506      Male
507       NaN
508      Male
509    Female
510      Male
511      Male
512      Male
513      Male
514      Male
515      Male
516    Female
517      Male
518      Male
519    Female
520      Male
521      Male
522      Male
523      Male
524      Male
525      Male
526      Male
527      Male
528      Male
529      Male
530      Male
531      Male
532      Male
533      Male
534    Female
535      Male
536      Male
537      Male
538      Male
539      Male
540    Female
541    Female
542    Female
543      Male
544    Female
545      Male
546      Male
547      Male
548    Female
549      Male
550      Male
551      Male
552      Male
553      Male
554      Male
555      Male
556    Female
557      Male
558      Male
559    Female
560      Male
561    Female
562      Male
563      Male
564      Male
565      Male
566      Male
567      Male
568    Female
569      Male
570      Male
571      Male
572      Male
573      Male
574      Male
575      Male
576       NaN
577      Male
578      Male
579      Male
580      Male
581      Male
582    Female
583      Male
584      Male
585      Male
586      Male
587    Female
588       NaN
589      Male
590      Male
591      Male
592       NaN
593      Male
594      Male
595      Male
596      Male
597      Male
598      Male
599      Male
600    Female
601      Male
602      Male
603      Male
604    Female
605      Male
606      Male
607      Male
608      Male
609    Female
610      Male
611      Male
612      Male
613    Female
614      Male
615      Male
616      Male
617      Male
618      Male
619      Male
620    Female
621      Male
622      Male
623      Male
624      Male
625      Male
626      Male
627      Male
628    Female
629      Male
630      Male
631      Male
632      Male
633      Male
634      Male
635    Female
636       NaN
637    Female
638      Male
639      Male
640      Male
641      Male
642      Male
643      Male
644    Female
645      Male
646      Male
647      Male
648      Male
649      Male
650      Male
651      Male
652      Male
653      Male
654      Male
655    Female
656      Male
657      Male
658    Female
659      Male
660      Male
661      Male
662      Male
663      Male
664      Male
665       NaN
666      Male
667      Male
668      Male
669      Male
670    Female
671      Male
672    Female
673      Male
674      Male
675      Male
676    Female
677    Female
678      Male
679      Male
680      Male
681      Male
682      Male
683      Male
684    Female
685      Male
686      Male
687      Male
688      Male
689      Male
690      Male
691      Male
692      Male
693    Female
694      Male
695      Male
696      Male
697      Male
698      Male
699      Male
700      Male
701      Male
702      Male
703    Female
704      Male
705      Male
706      Male
707      Male
708      Male
709    Female
710      Male
711      Male
712      Male
713      Male
714      Male
715    Female
716      Male
717      Male
718      Male
719    Female
720       NaN
721      Male
722      Male
723      Male
724    Female
725      Male
726    Female
727    Female
728      Male
729      Male
730    Female
731      Male
732    Female
733      Male
734      Male
735      Male
736      Male
737      Male
738    Female
739      Male
740      Male
741      Male
742      Male
743      Male
744      Male
745      Male
746      Male
747    Female
748      Male
749      Male
750      Male
751      Male
752       NaN
753    Female
754      Male
755      Male
756      Male
757      Male
758      Male
759    Female
760      Male
761      Male
762      Male
763      Male
764      Male
765      Male
766      Male
767      Male
768      Male
769      Male
770      Male
771      Male
772      Male
773      Male
774      Male
775      Male
776      Male
777    Female
778      Male
779      Male
780      Male
781      Male
782    Female
783    Female
784    Female
785      Male
786      Male
787      Male
788      Male
789      Male
790      Male
791    Female
792      Male
793      Male
794      Male
795      Male
796      Male
797    Female
798      Male
799      Male
800      Male
801      Male
802      Male
803      Male
804    Female
805      Male
806      Male
807      Male
808      Male
809      Male
810      Male
811      Male
812      Male
813      Male
814      Male
815      Male
816      Male
817    Female
818    Female
819      Male
820      Male
821      Male
822    Female
823       NaN
824    Female
825      Male
826      Male
827      Male
828      Male
829      Male
830      Male
831      Male
832      Male
833      Male
834      Male
835      Male
836      Male
837    Female
838    Female
839    Female
840      Male
841      Male
842      Male
843      Male
844      Male
845       NaN
846      Male
847    Female
848    Female
849      Male
850    Female
851      Male
852      Male
853      Male
854      Male
855      Male
856      Male
857      Male
858    Female
859       NaN
860      Male
861      Male
862      Male
863      Male
864      Male
865      Male
866    Female
867      Male
868    Female
869      Male
870    Female
871      Male
872      Male
873    Female
874      Male
875      Male
876      Male
877      Male
878      Male
879      Male
880    Female
881    Female
882      Male
883      Male
884    Female
885    Female
886      Male
887      Male
888    Female
889      Male
890      Male
891    Female
892      Male
893       NaN
894      Male
895      Male
896    Female
897      Male
898    Female
899      Male
900      Male
901      Male
902      Male
903      Male
904      Male
905      Male
906      Male
907    Female
908      Male
909    Female
910       NaN
911      Male
912    Female
913      Male
914      Male
915      Male
916    Female
917       NaN
918      Male
919      Male
920      Male
921      Male
922      Male
923      Male
924      Male
925    Female
926      Male
927      Male
928    Female
929    Female
930    Female
931      Male
932       NaN
933      Male
934      Male
935    Female
936      Male
937      Male
938      Male
939      Male
940      Male
941      Male
942      Male
943      Male
944      Male
945      Male
946    Female
947    Female
948      Male
949      Male
950    Female
951      Male
952      Male
953    Female
954      Male
955      Male
956      Male
957      Male
958      Male
959      Male
960      Male
961      Male
962      Male
963      Male
964      Male
965      Male
966      Male
967      Male
968      Male
969      Male
970      Male
971      Male
972      Male
973      Male
974    Female
975      Male
976      Male
977      Male
978      Male
979      Male
980      Male
Name: Gender, dtype: object

In [8]:
cr.Gender.describe()

count      957
unique       2
top       Male
freq       775
Name: Gender, dtype: object

In [9]:
cr.Property_Area.describe()

count           981
unique            3
top       Semiurban
freq            349
Name: Property_Area, dtype: object

In [10]:
cr.ApplicantIncome.describe()

count      981.000000
mean      5179.795107
std       5695.104533
min          0.000000
25%       2875.000000
50%       3800.000000
75%       5516.000000
max      81000.000000
Name: ApplicantIncome, dtype: float64

In [11]:
cr.describe(include='all')

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
count,981,957,978,956.000000,981,926,981.000000,981.000000,954.000000,961.000000,902.000000,981,981
unique,981,2,2,NaN,2,2,NaN,NaN,NaN,NaN,NaN,3,2
top,LP001002,Male,Yes,NaN,Graduate,No,NaN,NaN,NaN,NaN,NaN,Semiurban,Y
freq,1,775,631,NaN,763,807,NaN,NaN,NaN,NaN,NaN,349,712
mean,NaN,NaN,NaN,0.881799,NaN,NaN,5179.795107,1601.916330,142.511530,342.201873,0.835920,NaN,NaN
std,NaN,NaN,NaN,1.255623,NaN,NaN,5695.104533,2718.772806,77.421743,65.100602,0.370553,NaN,NaN
min,NaN,NaN,NaN,0.000000,NaN,NaN,0.000000,0.000000,9.000000,6.000000,0.000000,NaN,NaN
25%,NaN,NaN,NaN,0.000000,NaN,NaN,2875.000000,0.000000,100.000000,360.000000,1.000000,NaN,NaN
50%,NaN,NaN,NaN,0.000000,NaN,NaN,3800.000000,1110.000000,126.000000,360.000000,1.000000,NaN,NaN
75%,NaN,NaN,NaN,2.000000,NaN,NaN,5516.000000,2365.000000,162.000000,360.000000,1.000000,NaN,NaN
max,NaN,NaN,NaN,4.000000,NaN,NaN,81000.000000,41667.000000,700.000000,480.000000,1.000000,NaN,NaN

In [12]:
cr.ApplicantIncome.describe(percentiles = [.1,.2,.3,.4,.5,.6,.7,.8,.9,0.95,1])

count      981.000000
mean      5179.795107
std       5695.104533
min          0.000000
10%       2221.000000
20%       2609.000000
30%       3062.000000
40%       3413.000000
50%       3800.000000
60%       4301.000000
70%       5000.000000
80%       6080.000000
90%       8750.000000
95%      12500.000000
100%     81000.000000
max      81000.000000
Name: ApplicantIncome, dtype: float64

In [13]:
cr1=cr[(cr.ApplicantIncome > 4000) & (cr.Education =='Graduate') & (cr.Self_Employed =='Yes')]

In [14]:
cr1.head(20)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
5,LP001011,Male,Yes,2.0,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
25,LP001066,Male,Yes,0.0,Graduate,Yes,9560,0.0,191.0,360.0,1.0,Semiurban,Y
32,LP001097,Male,No,1.0,Graduate,Yes,4692,0.0,106.0,360.0,1.0,Rural,N
54,LP001186,Female,Yes,1.0,Graduate,Yes,11500,0.0,286.0,360.0,0.0,Urban,N
74,LP001253,Male,Yes,4.0,Graduate,Yes,5266,1774.0,187.0,360.0,1.0,Semiurban,Y
113,LP001392,Female,No,1.0,Graduate,Yes,7451,0.0,NaN,360.0,1.0,Semiurban,Y
128,LP001451,Male,Yes,1.0,Graduate,Yes,10513,3850.0,160.0,180.0,0.0,Urban,N
130,LP001469,Male,No,0.0,Graduate,Yes,20166,0.0,650.0,480.0,NaN,Urban,Y
142,LP001504,Male,No,0.0,Graduate,Yes,6950,0.0,175.0,180.0,1.0,Semiurban,Y
185,LP001640,Male,Yes,0.0,Graduate,Yes,39147,4750.0,120.0,360.0,1.0,Semiurban,Y
199,LP001673,Male,No,0.0,Graduate,Yes,11000,0.0,83.0,360.0,1.0,Urban,N
212,LP001713,Male,Yes,1.0,Graduate,Yes,7787,0.0,240.0,360.0,1.0,Urban,Y
229,LP001761,Male,No,0.0,Graduate,Yes,6400,0.0,200.0,360.0,1.0,Rural,Y
243,LP001807,Male,Yes,2.0,Graduate,Yes,6250,1300.0,108.0,360.0,1.0,Rural,Y
245,LP001813,Male,No,0.0,Graduate,Yes,6050,4333.0,120.0,180.0,1.0,Urban,N
254,LP001844,Male,No,0.0,Graduate,Yes,16250,0.0,192.0,360.0,0.0,Urban,N
264,LP001872,Male,No,0.0,Graduate,Yes,5166,0.0,128.0,360.0,1.0,Semiurban,Y
313,LP002008,Male,Yes,2.0,Graduate,Yes,5746,0.0,144.0,84.0,NaN,Rural,Y
319,LP002050,Male,Yes,1.0,Graduate,Yes,10000,0.0,155.0,360.0,1.0,Rural,N
325,LP002067,Male,Yes,1.0,Graduate,Yes,8666,4983.0,376.0,360.0,0.0,Rural,N

In [38]:
cr1.shape

(63, 13)

In [39]:
cr1.describe()

,Dependents,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,61.000000,63.000000,63.000000,61.000000,62.000000,60.000000
mean,1.081967,9552.095238,1009.428571,194.606557,336.387097,0.850000
std,1.268793,6207.388219,1875.198748,126.007047,78.040627,0.360085
min,0.000000,4246.000000,0.000000,50.000000,12.000000,0.000000
25%,0.000000,5825.500000,0.000000,116.000000,360.000000,1.000000
50%,1.000000,7451.000000,0.000000,160.000000,360.000000,1.000000
75%,2.000000,10277.500000,1417.500000,205.000000,360.000000,1.000000
max,4.000000,39147.000000,7873.000000,650.000000,480.000000,1.000000

In [57]:
cr.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [54]:
cr.Credit_History .describe()

count    902.000000
mean       0.835920
std        0.370553
min        0.000000
25%        1.000000
50%        1.000000
75%        1.000000
max        1.000000
Name: Credit_History, dtype: float64

In [45]:
cr.Gender = cr.Gender.fillna('Male')

In [48]:
cr.Married = cr.Married.fillna('No')

In [56]:
cr.Dependents = cr.Dependents.fillna(0)
cr.Self_Employed = cr.Self_Employed.fillna('Yes')
cr.LoanAmount  = cr.LoanAmount .fillna(cr.LoanAmount.mean())
cr.Loan_Amount_Term = cr.Loan_Amount_Term.fillna(cr.Loan_Amount_Term.mean())
cr.Credit_History = cr.Credit_History.fillna(0)

In [58]:
pr = pd.read_csv(r"D:Downloads/Datasets/Property_Price_Train.csv")

In [140]:
pr.isnull().sum()

Id                           0
Building_Class               0
Zoning_Class                 0
Lot_Extent                   0
Lot_Size                     0
Road_Type                    0
Lane_Type                    0
Property_Shape               0
Land_Outline                 0
Utility_Type                 0
Lot_Configuration            0
Property_Slope               0
Neighborhood                 0
Condition1                   0
Condition2                   0
House_Type                   0
House_Design                 0
Overall_Material             0
House_Condition              0
Construction_Year            0
Remodel_Year                 0
Roof_Design                  0
Roof_Quality                 0
Exterior1st                  0
Exterior2nd                  0
Brick_Veneer_Type            0
Brick_Veneer_Area            0
Exterior_Material            0
Exterior_Condition           0
Foundation_Type              0
Basement_Height              0
Basement_Condition           0
Exposure_Level               0
BsmtFinType1                 0
BsmtFinSF1                   0
BsmtFinType2                 0
BsmtFinSF2                   0
BsmtUnfSF                    0
Total_Basement_Area          0
Heating_Type                 0
Heating_Quality              0
Air_Conditioning             0
Electrical_System            0
First_Floor_Area             0
Second_Floor_Area            0
LowQualFinSF                 0
Grade_Living_Area            0
Underground_Full_Bathroom    0
Underground_Half_Bathroom    0
Full_Bathroom_Above_Grade    0
Half_Bathroom_Above_Grade    0
Bedroom_Above_Grade          0
Kitchen_Above_Grade          0
Kitchen_Quality              0
Rooms_Above_Grade            0
Functional_Rate              0
Fireplaces                   0
Fireplace_Quality            0
Garage                       0
Garage_Built_Year            0
Garage_Finish_Year           0
Garage_Size                  0
Garage_Area                  0
Garage_Quality               0
Garage_Condition             0
Pavedd_Drive                 0
W_Deck_Area                  0
Open_Lobby_Area              0
Enclosed_Lobby_Area          0
Three_Season_Lobby_Area      0
Screen_Lobby_Area            0
Pool_Area                    0
Pool_Quality                 0
Fence_Quality                0
Miscellaneous_Feature        0
Miscellaneous_Value          0
Month_Sold                   0
Year_Sold                    0
Sale_Type                    0
Sale_Condition               0
Sale_Price                   0
dtype: int64

In [92]:
pr.isnull().sum()*100/pr.shape[0] # here we are findinh out the percentage of null values in each column

Id                           0.0
Building_Class               0.0
Zoning_Class                 0.0
Lot_Extent                   0.0
Lot_Size                     0.0
Road_Type                    0.0
Lane_Type                    0.0
Property_Shape               0.0
Land_Outline                 0.0
Utility_Type                 0.0
Lot_Configuration            0.0
Property_Slope               0.0
Neighborhood                 0.0
Condition1                   0.0
Condition2                   0.0
House_Type                   0.0
House_Design                 0.0
Overall_Material             0.0
House_Condition              0.0
Construction_Year            0.0
Remodel_Year                 0.0
Roof_Design                  0.0
Roof_Quality                 0.0
Exterior1st                  0.0
Exterior2nd                  0.0
Brick_Veneer_Type            0.0
Brick_Veneer_Area            0.0
Exterior_Material            0.0
Exterior_Condition           0.0
Foundation_Type              0.0
Basement_Height              0.0
Basement_Condition           0.0
Exposure_Level               0.0
BsmtFinType1                 0.0
BsmtFinSF1                   0.0
BsmtFinType2                 0.0
BsmtFinSF2                   0.0
BsmtUnfSF                    0.0
Total_Basement_Area          0.0
Heating_Type                 0.0
Heating_Quality              0.0
Air_Conditioning             0.0
Electrical_System            0.0
First_Floor_Area             0.0
Second_Floor_Area            0.0
LowQualFinSF                 0.0
Grade_Living_Area            0.0
Underground_Full_Bathroom    0.0
Underground_Half_Bathroom    0.0
Full_Bathroom_Above_Grade    0.0
Half_Bathroom_Above_Grade    0.0
Bedroom_Above_Grade          0.0
Kitchen_Above_Grade          0.0
Kitchen_Quality              0.0
Rooms_Above_Grade            0.0
Functional_Rate              0.0
Fireplaces                   0.0
Fireplace_Quality            0.0
Garage                       0.0
Garage_Built_Year            0.0
Garage_Finish_Year           0.0
Garage_Size                  0.0
Garage_Area                  0.0
Garage_Quality               0.0
Garage_Condition             0.0
Pavedd_Drive                 0.0
W_Deck_Area                  0.0
Open_Lobby_Area              0.0
Enclosed_Lobby_Area          0.0
Three_Season_Lobby_Area      0.0
Screen_Lobby_Area            0.0
Pool_Area                    0.0
Pool_Quality                 0.0
Fence_Quality                0.0
Miscellaneous_Feature        0.0
Miscellaneous_Value          0.0
Month_Sold                   0.0
Year_Sold                    0.0
Sale_Type                    0.0
Sale_Condition               0.0
Sale_Price                   0.0
dtype: float64

In [68]:
pr.shape[0]

1459

In [62]:
pr.Lot_Extent = pr.Lot_Extent.fillna(pr.Lot_Extent.mean())

In [91]:
pr.Lane_Type = pr.Lane_Type.fillna('Grvl')
pr.Brick_Veneer_Type = pr.Brick_Veneer_Type.fillna('BrkFace')
pr.Brick_Veneer_Area = pr.Brick_Veneer_Area.fillna(pr.Brick_Veneer_Area.mean())
pr.Basement_Height = pr.Basement_Height.fillna('TA')
pr.Basement_Condition = pr.Basement_Condition.fillna('TA')
pr.Exposure_Level = pr.Exposure_Level.fillna('No')
pr.BsmtFinType1 = pr.BsmtFinType1.fillna('GLQ')
pr.BsmtFinType2 = pr.BsmtFinType2.fillna('Unf')
pr.Electrical_System = pr.Electrical_System.fillna('SBrkr')
pr.Fireplace_Quality = pr.Fireplace_Quality.fillna('TA')
pr.Garage = pr.Garage.fillna('Detchd')
pr.Garage_Built_Year = pr.Garage_Built_Year.fillna(1980)
pr.Garage_Finish_Year = pr.Garage_Finish_Year.fillna('Unf')
pr.Garage_Quality = pr.Garage_Quality.fillna('TA')
pr.Garage_Condition = pr.Garage_Condition.fillna('TA')
pr.Pool_Quality = pr.Pool_Quality.fillna('Fa')
pr.Fence_Quality = pr.Fence_Quality.fillna('MnPrv')
pr.Miscellaneous_Feature = pr.Miscellaneous_Feature.fillna('Shed')

In [88]:
pr.Miscellaneous_Feature.unique()

array([nan, 'Shed', 'Gar2', 'Othr', 'TenC'], dtype=object)

In [150]:
pr.Garage_Built_Year.describe()

count    1459.000000
mean     1978.598355
std        24.002610
min      1900.000000
25%      1962.000000
50%      1980.000000
75%      2001.000000
max      2010.000000
Name: Garage_Built_Year, dtype: float64

In [93]:
pr.head(20)

,Id,Building_Class,Zoning_Class,Lot_Extent,Lot_Size,Road_Type,Lane_Type,Property_Shape,Land_Outline,Utility_Type,Lot_Configuration,Property_Slope,Neighborhood,Condition1,Condition2,House_Type,House_Design,Overall_Material,House_Condition,Construction_Year,Remodel_Year,Roof_Design,Roof_Quality,Exterior1st,Exterior2nd,Brick_Veneer_Type,Brick_Veneer_Area,Exterior_Material,Exterior_Condition,Foundation_Type,Basement_Height,Basement_Condition,Exposure_Level,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,Total_Basement_Area,Heating_Type,Heating_Quality,Air_Conditioning,Electrical_System,First_Floor_Area,Second_Floor_Area,LowQualFinSF,Grade_Living_Area,Underground_Full_Bathroom,Underground_Half_Bathroom,Full_Bathroom_Above_Grade,Half_Bathroom_Above_Grade,Bedroom_Above_Grade,Kitchen_Above_Grade,Kitchen_Quality,Rooms_Above_Grade,Functional_Rate,Fireplaces,Fireplace_Quality,Garage,Garage_Built_Year,Garage_Finish_Year,Garage_Size,Garage_Area,Garage_Quality,Garage_Condition,Pavedd_Drive,W_Deck_Area,Open_Lobby_Area,Enclosed_Lobby_Area,Three_Season_Lobby_Area,Screen_Lobby_Area,Pool_Area,Pool_Quality,Fence_Quality,Miscellaneous_Feature,Miscellaneous_Value,Month_Sold,Year_Sold,Sale_Type,Sale_Condition,Sale_Price
0,1,60,RLD,65.000000,8450,Paved,Grvl,Reg,Lvl,AllPub,I,GS,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,SS,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PC,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,TF,0,TA,Attchd,2003.0,RFn,2,1085.793744,TA,TA,Y,163.788080,69.596115,20.337934,0,0,0,Fa,MnPrv,Shed,0,2,2008,WD,Normal,208500
1,2,20,RLD,80.000000,9600,Paved,Grvl,Reg,Lvl,AllPub,FR2P,GS,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,SS,MetalSd,MetalSd,None,0.0,TA,TA,CB,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,TF,1,TA,Attchd,1976.0,RFn,2,196.316304,TA,TA,Y,198.900074,74.716033,15.039392,0,0,0,Fa,MnPrv,Shed,0,5,2007,WD,Normal,181500
2,3,60,RLD,68.000000,11250,Paved,Grvl,IR1,Lvl,AllPub,I,GS,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,SS,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PC,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,TF,1,TA,Attchd,2001.0,RFn,2,218.068403,TA,TA,Y,26.127533,32.085268,-46.232198,0,0,0,Fa,MnPrv,Shed,0,9,2008,WD,Normal,223500
3,4,70,RLD,60.000000,9550,Paved,Grvl,IR1,Lvl,AllPub,C,GS,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,SS,Wd Sdng,Wd Shng,None,0.0,TA,TA,BT,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,TF,1,Gd,Detchd,1998.0,Unf,3,696.996439,TA,TA,Y,46.948018,40.181415,60.921821,0,0,0,Fa,MnPrv,Shed,0,2,2006,WD,Abnorml,140000
4,5,60,RLD,84.000000,14260,Paved,Grvl,IR1,Lvl,AllPub,FR2P,GS,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,SS,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PC,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,TF,1,TA,Attchd,2000.0,RFn,3,568.859882,TA,TA,Y,-10.626105,20.755323,21.788818,0,0,0,Fa,MnPrv,Shed,0,12,2008,WD,Normal,250000
5,6,50,RLD,85.000000,14115,Paved,Grvl,IR1,Lvl,AllPub,I,GS,Mitchel,Norm,Norm,1Fam,1.5Fin,5,5,1993,1995,Gable,SS,VinylSd,VinylSd,None,0.0,TA,TA,W,Gd,TA,No,GLQ,732,Unf,0,64,796,GasA,Ex,Y,SBrkr,796,566,0,1362,1,0,1,1,1,1,TA,5,TF,0,TA,Attchd,1993.0,Unf,2,703.481359,TA,TA,Y,0.621402,36.740335,70.350362,320,0,0,Fa,MnPrv,Shed,700,10,2009,WD,Normal,143000
6,7,20,RLD,75.000000,10084,Paved,Grvl,Reg,Lvl,AllPub,I,GS,Somerst,Norm,Norm,1Fam,1Story,8,5,2004,2005,Gable,SS,VinylSd,VinylSd,Stone,186.0,Gd,TA,PC,Ex,TA,Av,GLQ,1369,Unf,0,317,1686,GasA,Ex,Y,SBrkr,1694,0,0,1694,1,0,2,0,3,1,Gd,7,TF,1,Gd,Attchd,2004.0,RFn,2,555.415694,TA,TA,Y,39.047177,118.613457,-7.064622,0,0,0,Fa,MnPrv,Shed,0,8,2007,WD,Normal,307000
7,8,60,RLD,70.045833,10382,Paved,Grvl,IR1,Lvl,AllPub,C,GS,NWAmes,PosN,Norm,1Fam,2Story,7,6,1973,1973,Gable,SS,HdBoard,HdBoard,Stone,240.0,TA,TA,CB,Gd,TA,Mn,ALQ,859,BLQ,32,216,1107,GasA,Ex,Y,SBrkr,1107,983,0,2090,1,0,2,1,3,1,TA,7,TF,2,TA,Attchd,1973.0,RFn,2,737.632993,TA,TA,Y,201.101046,150.621507,76.923944,0,0,0,Fa,MnPrv,Shed,350,11,2009,WD,Normal,200000
8,9,50,RMD,51.000000,6120,Paved,Grvl,Reg,Lvl,AllPub,I,GS,OldTown,Artery,Norm,1Fam,1.5Fin,7,5,1931,1950,Gable,SS,BrkFace,Wd Shng,None,0.0,TA,TA,BT,TA,TA,No,Unf,0,Unf,0,952,952,GasA,Gd,Y,FuseF,1022,752,0,1774,0,0,2,0,2,2,TA,8,MD1,2,TA,Detchd,1931.0,Unf,2,424.620043,Fa,TA,Y,-24.044684,57.933986,78.563161,0,0,0,Fa,MnPrv,Shed,0,4,2008,WD,Abnorml,129900
9,10,190,RLD,50.000000,7420,Paved,Grvl,Reg,Lvl,AllPub,C,GS,BrkSide,Artery,Artery,2fmCon,1.5Unf,5,6,1939,1950,Gable,SS,MetalSd,MetalSd,None,0.0,TA,TA,BT,TA,TA,No,GLQ,851,Unf,0,140,991,GasA,Ex,Y,SBrkr,1077,0,0,1077,1,0,1,0,2,2,TA,5,TF,2,TA,Attchd,1939.0,RFn,1,632.539240,Gd,TA,Y,31.123219,59.827696,57.757631,0,0,0,Fa,MnPrv,Shed,0,1,2008,WD,Normal,118000
10,11,20,RLD,70.000000,11200,Paved,Grvl,Reg,Lvl,AllPub,I,GS,Sawyer,Norm,Norm,1Fam,1Story,5,5,1965,1965,Hip,SS,HdBoard,HdBoard,None,0.0,TA,TA,CB,TA,TA,No,Rec,906,Unf,0,134,1040,GasA,Ex,Y,SBrkr,1040,0,0,1040,1,0,1,0,3,1,TA,5,TF,0,TA,Detchd,1965.0,Unf,1,724.509882,TA,TA,Y,185.564715,22.519851,30.478397,0,0,0,Fa,MnPrv,Shed,0,2,2008,WD,Normal,129500
11,12,60,RLD,85.000000,11924,Paved,Grvl,IR1,Lvl,AllPub,I,GS,NridgHt,Norm,Norm,1Fam,2Story,9,5,2005,2006,Hip,SS,WdShing,Wd Shng,Stone,286.0,Ex,TA,PC,Ex,TA,No,GLQ,998,Unf,0,177,1175,GasA,Ex,Y,SBrkr,1182,1142,0,2324,1,0,3,0,4,1,Ex,11,TF,2,Gd,BuiltIn,2005.0,Fin,3,1004.528225,TA,TA,Y,141.036757,23.533718,103.990776,0,0,0,Fa,MnPrv,Shed,0,7,2006,New,Partial,345000
12,13,20,RLD,70.045833,12968,Paved,Grvl,IR2,Lvl,AllPub,I,GS,Sawyer,Norm,Norm,1Fam,1Story,5,6,1962,1962,Hip,SS,HdBoard,Plywood,None,0.0,TA,TA,CB,TA,TA,No,ALQ,737,Unf,0,175,912,GasA,TA,Y,SBrkr,912,0,0,912,1,0,1,0,2,1,TA,4,TF,0,TA,Detchd,1962.0,Unf,1,450.890177,TA,TA,Y,129.053257,98.369624,19.654410,0,176,0,Fa,MnPrv,Shed,0,9,2008,WD,Normal,144000
13,14,20,RLD,91.000000,10652,Paved,Grvl,IR1,Lvl,AllPub,I,GS,CollgCr,Norm,Norm,1Fam,1Story,7,5,2006,2007,Gable,SS,VinylSd,VinylSd,Stone,306.0,Gd,TA,PC,Gd,TA,Av,Unf,0,Unf,0,1494,1494,GasA,Ex,Y,SBrkr,1494,0,0,1494,0,0,2,0,3,1,Gd,7,TF,1,Gd,Attchd,2006.0,RFn,3,520.909729,TA,TA,Y,183.650980,-14.203250,75.125931,0,0,0,Fa,MnPrv,Shed,0,8,2007,New,Partial,279500
14,15,20,RLD,70.045833,10920,Paved,Grvl,IR1,Lvl,AllPub,C,GS,NAmes,Norm,Norm,1Fam,1Story,6,5,1960,1960,Hip,SS,MetalSd,MetalSd,BrkFace,212.0,TA,TA,CB,TA,TA,No,BLQ,733,Unf,0,520,1253,GasA,TA,Y,SBrkr,1253,0,0,1253,1,0,1,1,2,1,TA,5,TF,1,Fa,Attchd,1960.0,RFn,1,690.004706,TA,TA,Y,199.914549,6.475976,100.205972,0,0,0,Fa,GdWo,Shed,0,5,2008,WD,Normal,157000
15,16,45,RMD,51.000000,6120,Paved,Grvl,Reg,Lvl,AllPub,C,GS,BrkSide,Norm,Norm,1Fam,1.5Unf,7,8,1929,2001,Gable,SS,Wd Sdng,Wd Sdng,None,0.0,TA,TA,BT,TA,TA,No,Unf,0,Unf,0,832,832,GasA,Ex,Y,FuseA,854,0,0,854,0,0,1,0,2,1,TA,5,TF,0,TA,Detchd,1991.0,Unf,2,620.143245,TA,TA,Y,34.684125,105.163413,-58.762360,0,0,0,Fa,GdPrv,Shed,0,7,2007,WD,Normal,132000
16,17,20,RLD,70.045833,11241,Paved,Grvl,IR1,Lvl,AllPub,CulDSac,GS,NAmes,Norm,Norm,1Fam,1Story,6,7,1970,1970,Gable,SS,Wd Sdng,Wd Sdng,BrkFace,180.0,TA,TA,CB,TA,TA,No,ALQ,578,Unf,0,426,1004,GasA,Ex,Y,SBrkr,1004,0,0,1004,1,0,1,0,2,1,TA,5,TF,1,TA,Attchd,1970.0,Fin,2,506.333575,TA,TA,Y,195.926552,154.382283,119.542437,0,0,0,Fa,MnPrv,Shed,700,3,2010,WD,Normal,149000
17,18,90,RLD,72.000000,10791,Paved,Grvl,Reg,Lvl,AllPub,I,GS,Sawyer,Norm,Norm,Duplex,1Story,4,5,1967,1967,Gable,SS,MetalSd,MetalSd,None,0.0,TA,TA,SL,TA,TA,No,GLQ,0,Unf,0,0,0,GasA,TA,Y,SBrkr,1296,0,0,1296,0,0,2,0,2,2,TA,6,TF,0,TA,CarPort,1967.0,Unf,2,200.203887,TA,TA,Y,114.159130,4.615600,-13.433509,0,0,0,Fa,MnPrv,Shed,500,10,2006,WD,Normal,90000
18,19,20,RLD,66.000000,13695,Paved,Grvl,Reg,Lvl,AllPub,I,GS,SawyerW,RRAe,Norm,1Fam,1Story,5,5,2004,2004,Gable,SS,VinylSd,VinylSd,None,0.0,TA,TA,PC,TA,TA,No,GLQ,646,Unf,0,468,1114,GasA,Ex,Y,SBrkr,1114,0,0,1114,1,0,1,1,3,1,Gd,6,TF,0,TA,Detchd,2004.0,Unf,2,425.825400,TA,TA,Y,88.650284,40.701852,-20.468547,0,0,0,Fa,MnPrv,Shed,0,6,2008,WD,Normal,159000
19,20,20,RLD,70.000000,7560,Paved,Grvl,Reg,Lvl,AllPub,I,GS,NAmes,Norm,Norm,1Fam,1Story,5,6,1958,1965,Hip,SS,BrkFace,Plywood,None,0.0,TA,TA,CB,TA,TA,No,LwQ,504,Unf,0,525,1029,GasA,TA,Y,SBrkr,1339,0,0,1339,0,0,1,0,3,1,TA,6,MD1,0,TA,Attchd,1958.0,Unf,1,371.162160,TA,TA,Y,141.062720,146.374343,47.206992,0,0,0,Fa,MnPrv,Shed,0,5,2009,COD,Abnorml,139000

In [15]:
tc = pd.read_csv(r"D:Downloads/Datasets/Titanic.csv")

In [135]:
tc.head(20)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home_dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.000000,0,0,24160,211.3375,B5,S,2,160.809917,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.916700,1,2,113781,151.5500,C22 C26,S,11,160.809917,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.000000,1,2,113781,151.5500,C22 C26,S,13,160.809917,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.000000,1,2,113781,151.5500,C22 C26,S,13,135.000000,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.000000,1,2,113781,151.5500,C22 C26,S,13,160.809917,"Montreal, PQ / Chesterville, ON"
5,1,1,"Anderson, Mr. Harry",male,48.000000,0,0,19952,26.5500,E12,S,3,160.809917,"New York, NY"
6,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.000000,1,0,13502,77.9583,D7,S,10,160.809917,"Hudson, NY"
7,1,0,"Andrews, Mr. Thomas Jr",male,39.000000,0,0,112050,0.0000,A36,S,13,160.809917,"Belfast, NI"
8,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.000000,2,0,11769,51.4792,C101,S,D,160.809917,"Bayside, Queens, NY"
9,1,0,"Artagaveytia, Mr. Ramon",male,71.000000,0,0,PC 17609,49.5042,C23,C,13,22.000000,"Montevideo, Uruguay"
10,1,0,"Astor, Col. John Jacob",male,47.000000,1,0,PC 17757,227.5250,C62 C64,C,13,124.000000,"New York, NY"
11,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.000000,1,0,PC 17757,227.5250,C62 C64,C,4,160.809917,"New York, NY"
12,1,1,"Aubart, Mme. Leontine Pauline",female,24.000000,0,0,PC 17477,69.3000,B35,C,9,160.809917,"Paris, France"
13,1,1,"Barber, Miss. Ellen ""Nellie""",female,26.000000,0,0,19877,78.8500,C23,S,6,160.809917,"New York, NY"
14,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.000000,0,0,27042,30.0000,A23,S,B,160.809917,"Hessle, Yorks"
15,1,0,"Baumann, Mr. John D",male,29.881135,0,0,PC 17318,25.9250,C23,S,13,160.809917,"New York, NY"
16,1,0,"Baxter, Mr. Quigg Edmond",male,24.000000,0,1,PC 17558,247.5208,B58 B60,C,13,160.809917,"Montreal, PQ"
17,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.000000,0,1,PC 17558,247.5208,B58 B60,C,6,160.809917,"Montreal, PQ"
18,1,1,"Bazzani, Miss. Albina",female,32.000000,0,0,11813,76.2917,D15,C,8,160.809917,"New York, NY"
19,1,0,"Beattie, Mr. Thomson",male,36.000000,0,0,13050,75.2417,C6,C,A,160.809917,"Winnipeg, MN"

In [112]:
tc.describe()

,pclass,survived,age,sibsp,parch,fare,body
count,1309.000000,1309.000000,1046.000000,1309.000000,1309.000000,1308.000000,121.000000
mean,2.294882,0.381971,29.881135,0.498854,0.385027,33.295479,160.809917
std,0.837836,0.486055,14.413500,1.041658,0.865560,51.758668,97.696922
min,1.000000,0.000000,0.166700,0.000000,0.000000,0.000000,1.000000
25%,2.000000,0.000000,21.000000,0.000000,0.000000,7.895800,72.000000
50%,3.000000,0.000000,28.000000,0.000000,0.000000,14.454200,155.000000
75%,3.000000,1.000000,39.000000,1.000000,0.000000,31.275000,256.000000
max,3.000000,1.000000,80.000000,8.000000,9.000000,512.329200,328.000000

In [99]:
tc.shape

(1309, 14)

In [116]:
tc.fare.describe()

count    1308.000000
mean       33.295479
std        51.758668
min         0.000000
25%         7.895800
50%        14.454200
75%        31.275000
max       512.329200
Name: fare, dtype: float64

In [114]:
tc.home_dest.unique()

array(['St Louis, MO', 'Montreal, PQ / Chesterville, ON', 'New York, NY',
       'Hudson, NY', 'Belfast, NI', 'Bayside, Queens, NY',
       'Montevideo, Uruguay', 'Paris, France', nan, 'Hessle, Yorks',
       'Montreal, PQ', 'Winnipeg, MN', 'San Francisco, CA',
       'Dowagiac, MI', 'Stockholm, Sweden / Washington, DC',
       'Trenton, NJ', 'Glen Ridge, NJ', 'Youngstown, OH',
       'Birkdale, England Cleveland, Ohio', 'London / Winnipeg, MB',
       'Cooperstown, NY', 'St Leonards-on-Sea, England Ohio',
       'Los Angeles, CA', 'Pomeroy, WA', 'Omaha, NE', 'Philadelphia, PA',
       'Denver, CO', 'Belmont, MA', 'Washington, DC',
       'Austria-Hungary / Germantown, Philadelphia, PA',
       'Germantown, Philadelphia, PA', 'Bryn Mawr, PA',
       'Ascot, Berkshire / Rochester, NY', 'Little Onn Hall, Staffs',
       'Amenia, ND', 'New York, NY / Ithaca, NY', 'London, England',
       'Liverpool, England / Belfast', 'Stoughton, MA', 'Victoria, BC',
       'Lakewood, NJ', 'Roachdale, IN', 'Milwaukee, WI', 'Lima, Peru',
       'Calgary, AB', 'Deephaven, MN / Cedar Rapids, IA',
       'London / Paris', 'Mt Airy, Philadelphia, PA', 'Brookline, MA',
       'Brooklyn, NY', 'Winnipeg, MB', 'Westcliff-on-Sea, Essex',
       'Zurich, Switzerland', 'Scituate, MA',
       "St Anne's-on-Sea, Lancashire", 'Paris, France / New York, NY',
       'Greenwich, CT', 'Kingston, Surrey', 'London / Middlesex',
       'Brighton, MA', 'London / Birmingham', 'Chicago, IL',
       'Indianapolis, IN', 'New York, NY /  Stamford CT',
       'Paris, France New York, NY', 'Liverpool', 'Bennington, VT',
       'London', 'Buffalo, NY', 'Southington / Noank, CT', 'Boston, MA',
       'Portland, OR', 'Stockholm, Sweden', 'Springfield, MA',
       'London / New York, NY', 'Brockton, MA', 'Belgium  Montreal, PQ',
       'Vancouver, BC', 'Dorchester, MA', 'East Bridgewater, MA',
       'Fond du Lac, WI', 'Green Bay, WI', 'Lexington, MA',
       'Isle of Wight, England', 'Providence, RI', '?Havana, Cuba',
       'Belfast', 'Surbiton Hill, Surrey', 'Isleworth, England',
       'Madrid, Spain', 'Toronto, ON', 'Worcester, MA',
       'Rotterdam, Netherlands', 'Paris /  New York, NY', 'Seattle, WA',
       'London  Vancouver, BC', 'Haverford, PA / Cooperstown, NY',
       'Manchester, England', 'New York, NY / Greenwich CT', 'Duluth, MN',
       'Basel, Switzerland', 'New Britain, CT',
       'St James, Long Island, NY', 'Huntington, WV', 'Streatham, Surrey',
       'Minneapolis, MN', 'Tuxedo Park, NY',
       'Wimbledon Park, London / Hayling Island, Hants', 'Newark, NJ',
       'Haverford, PA', 'Gallipolis, Ohio / ? Paris / New York',
       'Cincinatti, OH', 'Haddenfield, NJ', 'London /  East Orange, NJ',
       'Albany, NY', 'Mexico City, Mexico', 'East Orange, NJ',
       'England Salt Lake City, Utah', 'Brunswick, ME',
       'New York, NY / Briarcliff Manor NY', 'Elkins Park, PA',
       'Geneva, Switzerland / Radnor, PA', 'Halifax, NS',
       'New York, NY / Washington, DC', 'Russia New York, NY',
       'Bryn Mawr, PA, USA', 'Buenos Aires, Argentina / New Jersey, NJ',
       'Cornwall, England Houghton, MI', 'Warwick, England',
       'West Hoboken, NJ', 'Penzance, Cornwall / Akron, OH', 'Guernsey',
       'Bristol, Avon / Jacksonville, FL',
       'Plymouth, Dorset / Houghton, MI', 'Jacksonville, FL',
       'Norwich / New York, NY', 'England',
       'Guntur, India / Benton Harbour, MI', 'Rochester, NY',
       'St Ives, Cornwall / Calumet, MI', 'Elmira, NY / Orange, NJ',
       'Lake Arthur, Chavez County, NM', 'London / Montreal, PQ',
       'Cape Town, South Africa / Seattle, WA',
       'Skara, Sweden / Rockford, IL',
       'Sittingbourne, England / San Diego, CA', 'Southsea, Hants',
       'Bangkok, Thailand / Roseville, IL', 'Mamaroneck, NY', 'Bronx, NY',
       'Cornwall / Spokane, WA', 'England / San Francisco, CA',
       'Hartford, Huntingdonshire', 'Helsinki, Finland Ashtabula, Ohio',
       'London / Fort Byron, NY',
       'Bishopstoke, Hants / Fayette Valley, ID', 'Pennsylvania',
       'Provo, UT', 'Upper Burma, India Pittsburgh, PA',
       'St Ives, Cornwall / Hancock, MI', 'Lyndhurst, England',
       'London / Staten Island, NY', 'Portugal / Sau Paulo, Brazil',
       'Lucca, Italy / California', 'Guernsey / Elizabeth, NJ',
       'New Forest, England', 'Southampton', 'Holley, NY',
       'Greenport, NY', 'Barcelona, Spain / Havana, Cuba',
       'England / Detroit, MI', 'Goteborg, Sweden / Rockford, IL',
       'Oslo, Norway Bayonne, NJ', 'England / Philadelphia, PA',
       'Cornwall / Houghton, MI', 'Janjgir, India / Pennsylvania',
       'Liverpool / Montreal, PQ', 'Cornwall / Clear Creek, CO',
       'Cornwall', 'Cornwall / Camden, NJ', 'West Kensington, London',
       'Clevedon, England', 'Auburn, NY', 'Detroit, MI',
       'Seattle, WA / Toledo, OH', 'Denmark Hill, Surrey / Chicago',
       'Walthamstow, England', 'Ilford, Essex / Winnipeg, MB',
       'Somerset / Bernardsville, NJ', 'India / Rapid City, SD',
       'West Hampstead, London / Neepawa, MB',
       'Kontiolahti, Finland / Detroit, MI', 'Cornwall / Akron, OH',
       'Devonport, England', 'England / Sacramento, CA', 'Tokyo, Japan',
       'Swindon, England', 'North Evington, England',
       'St Ives, Cornwall / Houghton, MI', 'Moscow / Bronx, NY',
       'India / Pittsburgh, PA', 'Harrisburg, PA', 'Glasgow / Bangor, ME',
       'Sweden / Arlington, NJ', 'Paris / Haiti',
       'Berne, Switzerland / Central City, IA', 'London / Chicago, IL',
       'Weston-Super-Mare, Somerset', 'Southampton / New York, NY',
       'Paris', 'Paris / Montreal, PQ', 'St Austall, Cornwall',
       'Weston-Super-Mare / Moose Jaw, SK', 'Sydney, Australia',
       'Sarnia, ON', 'England / Bennington, VT', 'Chelsea, London',
       'Harrow-on-the-Hill, Middlesex', 'Copenhagen, Denmark',
       'Guernsey / Montclair, NJ and/or Toledo, Ohio', 'Frankfort, KY',
       'Halesworth, England', 'Cambridge, MA', 'Nice, France',
       'Cornwall / Hancock, MI', 'Glasgow', 'Cologne, Germany',
       'Folkstone, Kent / New York, NY', 'Middleburg Heights, OH',
       'Pondersend, England / New Durham, NJ', 'Spain / Havana, Cuba',
       'Hamilton, ON', 'St Andrews, Guernsey', 'Woodford County, KY',
       'Gunnislake, England / Butte, MT', 'Ilfracombe, Devon',
       'Worcester, England', 'Russia', 'Denmark / New York, NY',
       'Milford, NH', 'Plymouth, Devon / Detroit, MI', 'Brighton, Sussex',
       'Elizabeth, NJ', 'Spain',
       'London, England / Marietta, Ohio and Milwaukee, WI',
       'Guernsey / Wilmington, DE', 'Hornsey, England', 'Deer Lodge, MT',
       'Finland / Minneapolis, MN', 'Finland / Washington, DC',
       'Sault St Marie, ON', 'Catford, Kent / Detroit, MI',
       'Columbus, OH', 'Bath, England / Massachusetts',
       'Plymouth, England', 'Barre, Co Washington, VT',
       'Bristol, England / New Britain, CT', 'Aberdeen / Portland, OR',
       'England / Hartford, CT', 'Bromsgrove, England / Montreal, PQ',
       'Bournmouth, England', 'Guernsey, England / Edgewood, RI',
       'Harrow, England', 'Yoevil, England / Cottage Grove, OR',
       'East Providence, RI', 'Norway Los Angeles, CA',
       'Perkins County, SD', 'Taalintehdas, Finland Hoboken, NJ',
       'Greensburg, PA', 'Asarum, Sweden Brooklyn, NY',
       'Bournemouth, England', 'Sweden Akeley, MN',
       'London, England Norfolk, VA', 'Syria Fredericksburg, VA',
       'England Albion, NY', 'Salo, Finland Astoria, OR', 'Argentina',
       'Lower Clapton, Middlesex or Erdington, Birmingham',
       'Windsor, England New York, NY', 'Bergen, Norway',
       'Sweden Winnipeg, MN', 'Ruotsinphyhtaa, Finland New York, NY',
       'Vadsbro, Sweden Ministee, MI', 'Hartford, CT',
       'Sweden Chicago, IL', 'Bulgaria Chicago, IL',
       'Altdorf, Switzerland', 'Sweden Joliet, IL',
       'Sweden  Worcester, MA', 'Sweden Worcester, MA',
       'Oskarshamn, Sweden Minneapolis, MN', 'Ottawa, ON',
       'Krakoryd, Sweden Bloomington, IL', 'Syria Youngstown, OH',
       'Ruotsinphytaa, Finland New York, NY', 'Syria New York, NY',
       'London Skanteales, NY', 'Syria Ottawa, ON',
       'England New York, NY', 'Krakudden, Sweden Moune, IL',
       'Tranvik, Finland New York', 'Syria', 'Hong Kong New York, NY',
       'Brennes, Norway New York', 'Stockholm, Sweden New York',
       'Syria Kent, ON', 'Ireland Chicago, IL',
       'Treherbert, Cardiff, Wales',
       'Kingwilliamstown, Co Cork, Ireland Glens Falls, NY',
       'Medeltorp, Sweden Chicago, IL', 'Bridgerule, Devon',
       'Broomfield, Chelmsford, England', 'Co Cork, Ireland Roxbury, MA',
       'Kingwilliamstown, Co Cork, Ireland New York, NY',
       'Co Cork, Ireland Charlestown, MA',
       'Co Sligo, Ireland New York, NY', 'Croatia',
       'Ireland Philadelphia, PA', 'Dagsas, Sweden Fower, MN',
       'Goteborg, Sweden Huntley, IL',
       'Co Longford, Ireland New York, NY',
       'Co Sligo, Ireland Hartford, CT', 'St Denys, Southampton, Hants',
       'Ireland New York, NY', 'Greece', 'Portugal',
       'London Brooklyn, NY', 'Co Limerick, Ireland Sherbrooke, PQ',
       'Ireland Brooklyn, NY', 'Ireland', 'Austria',
       'England Brooklyn, NY', 'Merrill, WI',
       'Bristol, England Cleveland, OH',
       'Bournemouth, England Newark, NJ', 'Austria-Hungary',
       'Australia Fingal, ND', 'Norrlot, Sweden Chicago, IL',
       'Co Athlone, Ireland New York, NY', 'Stanton, IA',
       'West Bromwich, England Pontiac, MI',
       'Liverpool, England Bedford, OH', 'Tampico, MT',
       'Belgium Detroit, MI', 'Devon, England Wichita, KS',
       'Bulgaria Coon Rapids, IA',
       'Kilmacowen, Co Sligo, Ireland New York, NY',
       'England Oglesby, IL', 'Union Hill, NJ', 'London New York, NY',
       'Austria Niagara Falls, NY', 'West Haven, CT',
       'Tofta, Sweden Joliet, IL', 'Karberg, Sweden Jerome Junction, AZ',
       'Effington Rut, SD', 'Illinois, USA',
       'Aughnacliff, Co Longford, Ireland New York, NY',
       'Italy Philadelphia, PA',
       'Rotherfield, Sussex, England Essex Co, MA',
       'Bridgwater, Somerset, England',
       'Co Clare, Ireland Washington, DC',
       'Strood, Kent, England Detroit, MI',
       'Wiltshire, England Niagara Falls, NY', 'Dorking, Surrey, England',
       'Foresvik, Norway Portland, ND', 'Waukegan, Chicago, IL',
       'Myren, Sweden New York, NY', 'Finland Sudbury, ON',
       'Oslo, Norway Cameron, WI', 'Antwerp, Belgium / Stanton, OH'],
      dtype=object)

In [120]:
tc.isnull().sum()

pclass       0
survived     0
name         0
sex          0
age          0
sibsp        0
parch        0
ticket       0
fare         0
cabin        0
embarked     0
boat         0
body         0
home_dest    0
dtype: int64

In [119]:
tc.age = tc.age.fillna(tc.age.mean())
tc.cabin = tc.cabin.fillna('C23')
tc.embarked = tc.embarked.fillna('S')
tc.boat = tc.boat.fillna('13')
tc.body = tc.body.fillna(tc.body.mean())
tc.home_dest = tc.home_dest.fillna('New York, NY')
tc.fare = tc.fare.fillna(tc.fare.mean())

In [16]:
bp=pd.read_csv(r"D:Downloads/Datasets/Patient_with_abnormal_bloodpressure.csv")

In [122]:
bp.head(20)

,Patient_Number,Blood_Pressure_Abnormality,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Pregnancy,Smoking,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
0,1,1,11.28,0.90,34,23,1,1.0,0,45961,48071,NaN,2,1,1
1,2,0,9.75,0.23,54,33,1,NaN,0,26106,25333,205.0,3,0,0
2,3,1,10.79,0.91,70,49,0,NaN,0,9995,29465,67.0,2,1,0
3,4,0,11.00,0.43,71,50,0,NaN,0,10635,7439,242.0,1,1,0
4,5,1,14.17,0.83,52,19,0,NaN,0,15619,49644,397.0,2,0,0
5,6,0,11.64,0.54,23,48,0,NaN,1,27042,7513,NaN,3,0,0
6,7,1,11.69,0.75,43,41,1,1.0,0,38369,32967,206.0,3,1,1
7,8,0,12.70,0.41,48,20,0,NaN,0,29781,26749,134.0,2,0,0
8,9,0,10.88,0.68,72,44,0,NaN,0,814,9607,99.0,3,0,0
9,10,1,14.56,0.61,40,44,0,NaN,0,1278,12715,95.0,2,0,0
10,11,1,8.58,0.13,70,28,1,NaN,0,48527,26178,46.0,1,1,1
11,12,1,12.77,0.10,35,17,0,NaN,0,22500,43040,382.0,3,1,0
12,13,1,16.40,0.45,31,50,0,NaN,1,25639,46997,41.0,3,0,1
13,14,0,16.42,0.13,75,40,0,NaN,1,11750,49800,308.0,3,0,1
14,15,0,11.97,0.76,18,32,0,NaN,0,14562,18007,NaN,2,1,1
15,16,1,10.96,0.10,43,27,1,1.0,0,7329,39018,495.0,1,1,0
16,17,1,11.98,0.06,65,28,1,NaN,0,29834,45217,377.0,2,0,0
17,18,1,11.60,0.09,61,44,0,NaN,0,49430,36987,153.0,2,0,0
18,19,1,8.99,0.17,18,30,1,1.0,0,43934,35603,NaN,3,1,0
19,20,1,16.55,0.91,18,38,0,NaN,0,25466,1807,NaN,3,1,1

In [123]:
bp.describe()

,Patient_Number,Blood_Pressure_Abnormality,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Pregnancy,Smoking,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
count,2000.000000,2000.000000,2000.000000,1908.000000,2000.000000,2000.000000,2000.000000,442.000000,2000.000000,2000.000000,2000.000000,1758.000000,2000.000000,2000.0000,2000.000000
mean,1000.500000,0.493500,11.710035,0.494817,46.558500,30.081500,0.496000,0.450226,0.509500,25254.424500,24926.097000,251.008532,2.012500,0.5050,0.443500
std,577.494589,0.500083,2.186701,0.291736,17.107832,11.761208,0.500109,0.498080,0.500035,14015.439623,14211.692586,143.651884,0.823822,0.5001,0.496922
min,1.000000,0.000000,8.100000,0.000000,18.000000,10.000000,0.000000,0.000000,0.000000,628.000000,22.000000,0.000000,1.000000,0.0000,0.000000
25%,500.750000,0.000000,10.147500,0.240000,32.000000,20.000000,0.000000,0.000000,0.000000,13605.750000,13151.750000,126.250000,1.000000,0.0000,0.000000
50%,1000.500000,0.000000,11.330000,0.490000,46.000000,30.000000,0.000000,0.000000,1.000000,25353.000000,25046.500000,250.000000,2.000000,1.0000,0.000000
75%,1500.250000,1.000000,12.945000,0.740000,62.000000,40.000000,1.000000,1.000000,1.000000,37382.250000,36839.750000,377.750000,3.000000,1.0000,1.000000
max,2000.000000,1.000000,17.560000,1.000000,75.000000,50.000000,1.000000,1.000000,1.000000,49980.000000,49976.000000,499.000000,3.000000,1.0000,1.000000

In [130]:
bp.isnull().sum()

Patient_Number                   0
Blood_Pressure_Abnormality       0
Level_of_Hemoglobin              0
Genetic_Pedigree_Coefficient     0
Age                              0
BMI                              0
Sex                              0
Pregnancy                        0
Smoking                          0
Physical_activity                0
salt_content_in_the_diet         0
alcohol_consumption_per_day      0
Level_of_Stress                  0
Chronic_kidney_disease           0
Adrenal_and_thyroid_disorders    0
dtype: int64

In [128]:
bp.Genetic_Pedigree_Coefficient = bp.Genetic_Pedigree_Coefficient.fillna(bp.Genetic_Pedigree_Coefficient.mean())
bp.Pregnancy = bp.Pregnancy.fillna(0)
bp.alcohol_consumption_per_day = bp.alcohol_consumption_per_day.fillna(bp.alcohol_consumption_per_day.mean())

In [149]:
pr.isnull().sum() [pr.isnull().sum() > 0]

Series([], dtype: int64)

In [17]:
pr = pd.read_csv(r"D:Downloads/Datasets/Property_Price_Train.csv")

In [153]:
pr.isnull().sum()[pr.isnull().sum() > 0]

Lot_Extent                259
Lane_Type                1368
Brick_Veneer_Type           8
Brick_Veneer_Area           8
Basement_Height            37
Basement_Condition         37
Exposure_Level             38
BsmtFinType1               37
BsmtFinType2               38
Electrical_System           1
Fireplace_Quality         689
Garage                     81
Garage_Built_Year          81
Garage_Finish_Year         81
Garage_Quality             81
Garage_Condition           81
Pool_Quality             1452
Fence_Quality            1178
Miscellaneous_Feature    1405
dtype: int64

In [154]:
pr.shape

(1459, 81)

In [156]:
pr1 = pr.drop(['Lane_Type' , 'Fireplace_Quality' , 'Pool_Quality' , 'Fence_Quality' , 'Miscellaneous_Feature'], axis = 1)

In [157]:
pr1.shape

(1459, 76)

In [166]:
pr1.isnull().sum()

Id                             0
Building_Class                 0
Zoning_Class                   0
Lot_Extent                   259
Lot_Size                       0
Road_Type                      0
Property_Shape                 0
Land_Outline                   0
Utility_Type                   0
Lot_Configuration              0
Property_Slope                 0
Neighborhood                   0
Condition1                     0
Condition2                     0
House_Type                     0
House_Design                   0
Overall_Material               0
House_Condition                0
Construction_Year              0
Remodel_Year                   0
Roof_Design                    0
Roof_Quality                   0
Exterior1st                    0
Exterior2nd                    0
Brick_Veneer_Type              8
Brick_Veneer_Area              8
Exterior_Material              0
Exterior_Condition             0
Foundation_Type                0
Basement_Height               37
Basement_Condition            37
Exposure_Level                38
BsmtFinType1                  37
BsmtFinSF1                     0
BsmtFinType2                  38
BsmtFinSF2                     0
BsmtUnfSF                      0
Total_Basement_Area            0
Heating_Type                   0
Heating_Quality                0
Air_Conditioning               0
Electrical_System              1
First_Floor_Area               0
Second_Floor_Area              0
LowQualFinSF                   0
Grade_Living_Area              0
Underground_Full_Bathroom      0
Underground_Half_Bathroom      0
Full_Bathroom_Above_Grade      0
Half_Bathroom_Above_Grade      0
Bedroom_Above_Grade            0
Kitchen_Above_Grade            0
Kitchen_Quality                0
Rooms_Above_Grade              0
Functional_Rate                0
Fireplaces                     0
Garage                        81
Garage_Built_Year             81
Garage_Finish_Year            81
Garage_Size                    0
Garage_Area                    0
Garage_Quality                81
Garage_Condition              81
Pavedd_Drive                   0
W_Deck_Area                    0
Open_Lobby_Area                0
Enclosed_Lobby_Area            0
Three_Season_Lobby_Area        0
Screen_Lobby_Area              0
Pool_Area                      0
Miscellaneous_Value            0
Month_Sold                     0
Year_Sold                      0
Sale_Type                      0
Sale_Condition                 0
Sale_Price                     0
dtype: int64

In [170]:
pr1.rename({"Three_Season_Lobby_Area" : "THLA", "Underground_Full_Bathroom" : "UG_Full_Bathroom"} , inplace = True , axis = 1)

In [171]:
pr1.head(2)

,Id,Building_Class,Zoning_Class,Lot_Extent,Lot_Size,Road_Type,Property_Shape,Land_Outline,Utility_Type,Lot_Configuration,Property_Slope,Neighborhood,Condition1,Condition2,House_Type,House_Design,Overall_Material,House_Condition,Construction_Year,Remodel_Year,Roof_Design,Roof_Quality,Exterior1st,Exterior2nd,Brick_Veneer_Type,Brick_Veneer_Area,Exterior_Material,Exterior_Condition,Foundation_Type,Basement_Height,Basement_Condition,Exposure_Level,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,Total_Basement_Area,Heating_Type,Heating_Quality,Air_Conditioning,Electrical_System,First_Floor_Area,Second_Floor_Area,LowQualFinSF,Grade_Living_Area,UG_Full_Bathroom,Underground_Half_Bathroom,Full_Bathroom_Above_Grade,Half_Bathroom_Above_Grade,Bedroom_Above_Grade,Kitchen_Above_Grade,Kitchen_Quality,Rooms_Above_Grade,Functional_Rate,Fireplaces,Garage,Garage_Built_Year,Garage_Finish_Year,Garage_Size,Garage_Area,Garage_Quality,Garage_Condition,Pavedd_Drive,W_Deck_Area,Open_Lobby_Area,Enclosed_Lobby_Area,THLA,Screen_Lobby_Area,Pool_Area,Miscellaneous_Value,Month_Sold,Year_Sold,Sale_Type,Sale_Condition,Sale_Price
0,1,60,RLD,65.0,8450,Paved,Reg,Lvl,AllPub,I,GS,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,SS,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PC,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,TF,0,Attchd,2003.0,RFn,2,1085.793744,TA,TA,Y,163.788080,69.596115,20.337934,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RLD,80.0,9600,Paved,Reg,Lvl,AllPub,FR2P,GS,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,SS,MetalSd,MetalSd,None,0.0,TA,TA,CB,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,TF,1,Attchd,1976.0,RFn,2,196.316304,TA,TA,Y,198.900074,74.716033,15.039392,0,0,0,0,5,2007,WD,Normal,181500

In [234]:
cr = pd.read_csv(r"D:Downloads/Datasets/CreditRisk.csv")

In [215]:
cr.shape

(981, 13)

In [194]:
cr1 = cr.iloc[[9,99,499,549],[0,4,6,9]]

In [181]:
cr1

      Loan_ID Education  ApplicantIncome  Loan_Amount_Term
9    LP001020  Graduate            12841             360.0
99   LP001343  Graduate             1759             360.0
499  LP002602  Graduate             6283             360.0
549  LP002777  Graduate             2785             360.0

In [182]:
cr2= cr.iloc[[9,99,499,549],:]
cr2

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
9,LP001020,Male,Yes,1.0,Graduate,No,12841,10968.0,349.0,360.0,1.0,Semiurban,N
99,LP001343,Male,Yes,0.0,Graduate,No,1759,3541.0,131.0,360.0,1.0,Semiurban,Y
499,LP002602,Male,No,0.0,Graduate,No,6283,4416.0,209.0,360.0,0.0,Rural,N
549,LP002777,Male,Yes,0.0,Graduate,No,2785,2016.0,110.0,360.0,1.0,Rural,Y

In [193]:
cr3 = cr.iloc[ : , [0,4,6,9,12]]
cr3

      Loan_ID     Education  ApplicantIncome  Loan_Amount_Term Loan_Status
0    LP001002      Graduate             5849             360.0           Y
1    LP001003      Graduate             4583             360.0           N
2    LP001005      Graduate             3000             360.0           Y
3    LP001006  Not Graduate             2583             360.0           Y
4    LP001008      Graduate             6000             360.0           Y
5    LP001011      Graduate             5417             360.0           Y
6    LP001013  Not Graduate             2333             360.0           Y
7    LP001014      Graduate             3036             360.0           N
8    LP001018      Graduate             4006             360.0           Y
9    LP001020      Graduate            12841             360.0           N
10   LP001024      Graduate             3200             360.0           Y
11   LP001027      Graduate             2500             360.0           Y
12   LP001028      Graduate             3073             360.0           Y
13   LP001029      Graduate             1853             360.0           N
14   LP001030      Graduate             1299             120.0           Y
15   LP001032      Graduate             4950             360.0           Y
16   LP001034  Not Graduate             3596             240.0           Y
17   LP001036      Graduate             3510             360.0           N
18   LP001038  Not Graduate             4887             360.0           N
19   LP001041      Graduate             2600               NaN           Y
20   LP001043  Not Graduate             7660             360.0           N
21   LP001046      Graduate             5955             360.0           Y
22   LP001047  Not Graduate             2600             360.0           N
23   LP001050  Not Graduate             3365             360.0           N
24   LP001052      Graduate             3717             360.0           N
25   LP001066      Graduate             9560             360.0           Y
26   LP001068      Graduate             2799             360.0           Y
27   LP001073  Not Graduate             4226             360.0           Y
28   LP001086  Not Graduate             1442             360.0           N
29   LP001087      Graduate             3750             360.0           Y
30   LP001091      Graduate             4166             360.0           N
31   LP001095      Graduate             3167             360.0           N
32   LP001097      Graduate             4692             360.0           N
33   LP001098      Graduate             3500             360.0           Y
34   LP001100      Graduate            12500             360.0           N
35   LP001106      Graduate             2275             360.0           Y
36   LP001109      Graduate             1828               NaN           N
37   LP001112      Graduate             3667             360.0           Y
38   LP001114      Graduate             4166             360.0           Y
39   LP001116  Not Graduate             3748             360.0           Y
40   LP001119      Graduate             3600             360.0           N
41   LP001120      Graduate             1800             360.0           Y
42   LP001123      Graduate             2400             360.0           Y
43   LP001131      Graduate             3941             360.0           Y
44   LP001136  Not Graduate             4695               NaN           Y
45   LP001137      Graduate             3410               NaN           Y
46   LP001138      Graduate             5649             360.0           Y
47   LP001144      Graduate             5821             360.0           Y
48   LP001146      Graduate             2645             360.0           N
49   LP001151      Graduate             4000             360.0           Y
50   LP001155  Not Graduate             1928             360.0           Y
51   LP001157      Graduate             3086             360.0           Y
52   LP001164      Graduate             4230             360.0           N
53   LP001179      Graduate             4616             360.0           N
54   LP001186      Graduate            11500             360.0           N
55   LP001194      Graduate             2708             360.0           Y
56   LP001195      Graduate             2132             360.0           Y
57   LP001197      Graduate             3366             360.0           N
58   LP001198      Graduate             8080             360.0           Y
59   LP001199  Not Graduate             3357             360.0           Y
60   LP001205      Graduate             2500             360.0           Y
61   LP001206      Graduate             3029             360.0           Y
62   LP001207  Not Graduate             2609             180.0           N
63   LP001213      Graduate             4945             360.0           N
64   LP001222      Graduate             4166             360.0           N
65   LP001225      Graduate             5726             360.0           N
66   LP001228  Not Graduate             3200             180.0           N
67   LP001233      Graduate            10750             360.0           Y
68   LP001238  Not Graduate             7100              60.0           Y
69   LP001241      Graduate             4300             360.0           N
70   LP001243      Graduate             3208             360.0           Y
71   LP001245  Not Graduate             1875             360.0           Y
72   LP001248      Graduate             3500             300.0           Y
73   LP001250  Not Graduate             4755               NaN           N
74   LP001253      Graduate             5266             360.0           Y
75   LP001255      Graduate             3750             480.0           N
76   LP001256      Graduate             3750             360.0           N
77   LP001259      Graduate             1000             360.0           N
78   LP001263      Graduate             3167             300.0           N
79   LP001264  Not Graduate             3333             360.0           Y
80   LP001265      Graduate             3846             360.0           Y
81   LP001266      Graduate             2395             360.0           Y
82   LP001267      Graduate             1378             360.0           N
83   LP001273      Graduate             6000             360.0           N
84   LP001275      Graduate             3988             240.0           Y
85   LP001279      Graduate             2366             360.0           Y
86   LP001280  Not Graduate             3333             360.0           Y
87   LP001282      Graduate             2500             360.0           Y
88   LP001289      Graduate             8566             360.0           Y
89   LP001310      Graduate             5695             360.0           Y
90   LP001316      Graduate             2958             360.0           Y
91   LP001318      Graduate             6250             180.0           Y
92   LP001319  Not Graduate             3273             360.0           Y
93   LP001322      Graduate             4133             360.0           Y
94   LP001325  Not Graduate             3620             120.0           Y
95   LP001326      Graduate             6782             360.0           N
96   LP001327      Graduate             2484             360.0           Y
97   LP001333      Graduate             1977             360.0           Y
98   LP001334  Not Graduate             4188             180.0           Y
99   LP001343      Graduate             1759             360.0           Y
100  LP001345  Not Graduate             4288             180.0           Y
101  LP001349      Graduate             4843             360.0           Y
102  LP001350      Graduate            13650             360.0           Y
103  LP001356      Graduate             4652             360.0           Y
104  LP001357      Graduate             3816             360.0           Y
105  LP001367      Graduate             3052             360.0           Y
106  LP001369      Graduate            11417             360.0           Y
107  LP001370  Not Graduate             7333             360.0           N
108  LP001379      Graduate             3800             360.0           N
109  LP001384  Not Graduate             2071             480.0           Y
110  LP001385      Graduate             5316             360.0           Y
111  LP001387      Graduate             2929             360.0           Y
112  LP001391  Not Graduate             3572               NaN           N
113  LP001392      Graduate             7451             360.0           Y
114  LP001398      Graduate             5050             360.0           Y
115  LP001401      Graduate            14583             180.0           Y
116  LP001404      Graduate             3167             360.0           Y
117  LP001405      Graduate             2214             360.0           Y
118  LP001421      Graduate             5568             360.0           N
119  LP001422      Graduate            10408             360.0           Y
120  LP001426      Graduate             5667             360.0           Y
121  LP001430      Graduate             4166             360.0           Y
122  LP001431      Graduate             2137             360.0           Y
123  LP001432      Graduate             2957             360.0           Y
124  LP001439  Not Graduate             4300             360.0           Y
125  LP001443      Graduate             3692             360.0           Y
126  LP001448      Graduate            23803             360.0           Y
127  LP001449      Graduate             3865             360.0           Y
128  LP001451      Graduate            10513             180.0           N
129  LP001465      Graduate             6080             360.0           N
130  LP001469      Graduate            20166             480.0           Y
131  LP001473      Graduate             2014             360.0           Y
132  LP001478      Graduate             2718             360.0           Y
133  LP001482      Graduate             3459             120.0           Y
134  LP001487      Graduate             4895             360.0           Y
135  LP001488      Graduate             4000             360.0           N
136  LP001489      Graduate             4583             360.0           N
137  LP001491      Graduate             3316             360.0           Y
138  LP001492      Graduate            14999             360.0           N
139  LP001493  Not Graduate             4200             360.0           N
140  LP001497      Graduate             5042             360.0           N
141  LP001498      Graduate             5417             360.0           Y
142  LP001504      Graduate             6950             180.0           Y
143  LP001507      Graduate             2698             360.0           Y
144  LP001508      Graduate            11757             180.0           Y
145  LP001514      Graduate             2330             360.0           Y
146  LP001516      Graduate            14866             360.0           Y
147  LP001518      Graduate             1538             360.0           Y
148  LP001519      Graduate            10000             360.0           N
149  LP001520      Graduate             4860             360.0           Y
150  LP001528      Graduate             6277             360.0           N
151  LP001529      Graduate             2577             360.0           Y
152  LP001531      Graduate             9166             360.0           N
153  LP001532  Not Graduate             2281             360.0           N
154  LP001535      Graduate             3254             360.0           Y
155  LP001536      Graduate            39999             180.0           Y
156  LP001541      Graduate             6000             360.0           Y
157  LP001543      Graduate             9538             360.0           Y
158  LP001546      Graduate             2980             360.0           Y
159  LP001552      Graduate             4583             360.0           Y
160  LP001560  Not Graduate             1863             360.0           Y
161  LP001562      Graduate             7933             360.0           N
162  LP001565      Graduate             3089             360.0           N
163  LP001570      Graduate             4167             360.0           Y
164  LP001572      Graduate             9323             180.0           Y
165  LP001574      Graduate             3707               NaN           Y
166  LP001577      Graduate             4583             360.0           N
167  LP001578      Graduate             2439             360.0           Y
168  LP001579      Graduate             2237             480.0           N
169  LP001580      Graduate             8000             360.0           Y
170  LP001581  Not Graduate             1820             360.0           Y
171  LP001585      Graduate            51763             300.0           Y
172  LP001586  Not Graduate             3522             180.0           N
173  LP001594      Graduate             5708             360.0           Y
174  LP001603  Not Graduate             4344             360.0           N
175  LP001606      Graduate             3497             360.0           Y
176  LP001608      Graduate             2045             360.0           Y
177  LP001610      Graduate             5516             360.0           N
178  LP001616      Graduate             3750             360.0           Y
179  LP001630  Not Graduate             2333             480.0           N
180  LP001633      Graduate             6400             360.0           N
181  LP001634      Graduate             1916             360.0           N
182  LP001636      Graduate             4600             180.0           Y
183  LP001637      Graduate            33846             360.0           N
184  LP001639      Graduate             3625             360.0           Y
185  LP001640      Graduate            39147             360.0           Y
186  LP001641      Graduate             2178             300.0           N
187  LP001643      Graduate             2383             360.0           Y
188  LP001644      Graduate              674             360.0           Y
189  LP001647      Graduate             9328             180.0           Y
190  LP001653  Not Graduate             4885             360.0           Y
191  LP001656      Graduate            12000             360.0           N
192  LP001657  Not Graduate             6033             360.0           N
193  LP001658      Graduate             3858             360.0           Y
194  LP001664      Graduate             4191             360.0           Y
195  LP001665      Graduate             3125             360.0           N
196  LP001666      Graduate             8333             360.0           Y
197  LP001669  Not Graduate             1907               NaN           Y
198  LP001671      Graduate             3416             360.0           Y
199  LP001673      Graduate            11000             360.0           N
200  LP001674  Not Graduate             2600             360.0           Y
201  LP001677      Graduate             4923             360.0           Y
202  LP001682  Not Graduate             3992             180.0           N
203  LP001688  Not Graduate             3500             360.0           Y
204  LP001691  Not Graduate             3917             360.0           Y
205  LP001692  Not Graduate             4408             360.0           Y
206  LP001693      Graduate             3244             360.0           Y
207  LP001698  Not Graduate             3975             360.0           Y
208  LP001699      Graduate             2479             360.0           Y
209  LP001702      Graduate             3418             360.0           N
210  LP001708      Graduate            10000             360.0           N
211  LP001711      Graduate             3430             360.0           N
212  LP001713      Graduate             7787             360.0           Y
213  LP001715  Not Graduate             5703             360.0           Y
214  LP001716      Graduate             3173             360.0           Y
215  LP001720  Not Graduate             3850             360.0           Y
216  LP001722      Graduate              150             360.0           N
217  LP001726      Graduate             3727             360.0           Y
218  LP001732      Graduate             5000             360.0           N
219  LP001734      Graduate             4283             360.0           Y
220  LP001736      Graduate             2221             360.0           N
221  LP001743      Graduate             4009             360.0           Y
222  LP001744      Graduate             2971             360.0           Y
223  LP001749      Graduate             7578               NaN           Y
224  LP001750      Graduate             6250             360.0           Y
225  LP001751      Graduate             3250             360.0           N
226  LP001754  Not Graduate             4735             360.0           N
227  LP001758      Graduate             6250             360.0           Y
228  LP001760      Graduate             4758             480.0           Y
229  LP001761      Graduate             6400             360.0           Y
230  LP001765      Graduate             2491             360.0           Y
231  LP001768      Graduate             3716             180.0           Y
232  LP001770  Not Graduate             3189               NaN           Y
233  LP001776      Graduate             8333             360.0           Y
234  LP001778      Graduate             3155             360.0           Y
235  LP001784      Graduate             5500             360.0           Y
236  LP001786      Graduate             5746             360.0           N
237  LP001788      Graduate             3463             360.0           Y
238  LP001790      Graduate             3812             360.0           Y
239  LP001792      Graduate             3315             360.0           Y
240  LP001798      Graduate             5819             360.0           Y
241  LP001800  Not Graduate             2510             180.0           N
242  LP001806      Graduate             2965              60.0           Y
243  LP001807      Graduate             6250             360.0           Y
244  LP001811  Not Graduate             3406             360.0           Y
245  LP001813      Graduate             6050             180.0           N
246  LP001814      Graduate             9703             360.0           Y
247  LP001819  Not Graduate             6608             180.0           Y
248  LP001824      Graduate             2882             480.0           Y
249  LP001825      Graduate             1809             360.0           Y
250  LP001835  Not Graduate             1668             360.0           N
251  LP001836      Graduate             3427             360.0           N
252  LP001841  Not Graduate             2583             360.0           Y
253  LP001843  Not Graduate             2661             180.0           Y
254  LP001844      Graduate            16250             360.0           N
255  LP001846      Graduate             3083             360.0           Y
256  LP001849  Not Graduate             6045             360.0           N
257  LP001854      Graduate             5250             360.0           N
258  LP001859      Graduate            14683             360.0           N
259  LP001864  Not Graduate             4931             360.0           N
260  LP001865      Graduate             6083             360.0           Y
261  LP001868      Graduate             2060             360.0           Y
262  LP001870      Graduate             3481              36.0           N
263  LP001871      Graduate             7200             360.0           Y
264  LP001872      Graduate             5166             360.0           Y

In [204]:
df1 = cr.iloc[:,[5,6,7,8,9,10,11,12]]
df1

,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,No,5849,0.000000,NaN,360.0,1.0,Urban,Y
1,No,4583,1508.000000,128.0,360.0,1.0,Rural,N
2,Yes,3000,0.000000,66.0,360.0,1.0,Urban,Y
3,No,2583,2358.000000,120.0,360.0,1.0,Urban,Y
4,No,6000,0.000000,141.0,360.0,1.0,Urban,Y
5,Yes,5417,4196.000000,267.0,360.0,1.0,Urban,Y
6,No,2333,1516.000000,95.0,360.0,1.0,Urban,Y
7,No,3036,2504.000000,158.0,360.0,0.0,Semiurban,N
8,No,4006,1526.000000,168.0,360.0,1.0,Urban,Y
9,No,12841,10968.000000,349.0,360.0,1.0,Semiurban,N
10,No,3200,700.000000,70.0,360.0,1.0,Urban,Y
11,NaN,2500,1840.000000,109.0,360.0,1.0,Urban,Y
12,No,3073,8106.000000,200.0,360.0,1.0,Urban,Y
13,No,1853,2840.000000,114.0,360.0,1.0,Rural,N
14,No,1299,1086.000000,17.0,120.0,1.0,Urban,Y
15,No,4950,0.000000,125.0,360.0,1.0,Urban,Y
16,No,3596,0.000000,100.0,240.0,NaN,Urban,Y
17,No,3510,0.000000,76.0,360.0,0.0,Urban,N
18,No,4887,0.000000,133.0,360.0,1.0,Rural,N
19,NaN,2600,3500.000000,115.0,NaN,1.0,Urban,Y
20,No,7660,0.000000,104.0,360.0,0.0,Urban,N
21,No,5955,5625.000000,315.0,360.0,1.0,Urban,Y
22,No,2600,1911.000000,116.0,360.0,0.0,Semiurban,N
23,No,3365,1917.000000,112.0,360.0,0.0,Rural,N
24,NaN,3717,2925.000000,151.0,360.0,NaN,Semiurban,N
25,Yes,9560,0.000000,191.0,360.0,1.0,Semiurban,Y
26,No,2799,2253.000000,122.0,360.0,1.0,Semiurban,Y
27,No,4226,1040.000000,110.0,360.0,1.0,Urban,Y
28,No,1442,0.000000,35.0,360.0,1.0,Urban,N
29,NaN,3750,2083.000000,120.0,360.0,1.0,Semiurban,Y
30,NaN,4166,3369.000000,201.0,360.0,NaN,Urban,N
31,No,3167,0.000000,74.0,360.0,1.0,Urban,N
32,Yes,4692,0.000000,106.0,360.0,1.0,Rural,N
33,No,3500,1667.000000,114.0,360.0,1.0,Semiurban,Y
34,No,12500,3000.000000,320.0,360.0,1.0,Rural,N
35,No,2275,2067.000000,NaN,360.0,1.0,Urban,Y
36,No,1828,1330.000000,100.0,NaN,0.0,Urban,N
37,No,3667,1459.000000,144.0,360.0,1.0,Semiurban,Y
38,No,4166,7210.000000,184.0,360.0,1.0,Urban,Y
39,No,3748,1668.000000,110.0,360.0,1.0,Semiurban,Y
40,No,3600,0.000000,80.0,360.0,1.0,Urban,N
41,No,1800,1213.000000,47.0,360.0,1.0,Urban,Y
42,No,2400,0.000000,75.0,360.0,NaN,Urban,Y
43,No,3941,2336.000000,134.0,360.0,1.0,Semiurban,Y
44,Yes,4695,0.000000,96.0,NaN,1.0,Urban,Y
45,No,3410,0.000000,88.0,NaN,1.0,Urban,Y
46,No,5649,0.000000,44.0,360.0,1.0,Urban,Y
47,No,5821,0.000000,144.0,360.0,1.0,Urban,Y
48,No,2645,3440.000000,120.0,360.0,0.0,Urban,N
49,No,4000,2275.000000,144.0,360.0,1.0,Semiurban,Y
50,No,1928,1644.000000,100.0,360.0,1.0,Semiurban,Y
51,No,3086,0.000000,120.0,360.0,1.0,Semiurban,Y
52,No,4230,0.000000,112.0,360.0,1.0,Semiurban,N
53,No,4616,0.000000,134.0,360.0,1.0,Urban,N
54,Yes,11500,0.000000,286.0,360.0,0.0,Urban,N
55,No,2708,1167.000000,97.0,360.0,1.0,Semiurban,Y
56,No,2132,1591.000000,96.0,360.0,1.0,Semiurban,Y
57,No,3366,2200.000000,135.0,360.0,1.0,Rural,N
58,No,8080,2250.000000,180.0,360.0,1.0,Urban,Y
59,No,3357,2859.000000,144.0,360.0,1.0,Urban,Y
60,No,2500,3796.000000,120.0,360.0,1.0,Urban,Y
61,No,3029,0.000000,99.0,360.0,1.0,Urban,Y
62,Yes,2609,3449.000000,165.0,180.0,0.0,Rural,N
63,No,4945,0.000000,NaN,360.0,0.0,Rural,N
64,No,4166,0.000000,116.0,360.0,0.0,Semiurban,N
65,No,5726,4595.000000,258.0,360.0,1.0,Semiurban,N
66,No,3200,2254.000000,126.0,180.0,0.0,Urban,N
67,No,10750,0.000000,312.0,360.0,1.0,Urban,Y
68,Yes,7100,0.000000,125.0,60.0,1.0,Urban,Y
69,No,4300,0.000000,136.0,360.0,0.0,Semiurban,N
70,No,3208,3066.000000,172.0,360.0,1.0,Urban,Y
71,Yes,1875,1875.000000,97.0,360.0,1.0,Semiurban,Y
72,No,3500,0.000000,81.0,300.0,1.0,Semiurban,Y
73,No,4755,0.000000,95.0,NaN,0.0,Semiurban,N
74,Yes,5266,1774.000000,187.0,360.0,1.0,Semiurban,Y
75,No,3750,0.000000,113.0,480.0,1.0,Urban,N
76,No,3750,4750.000000,176.0,360.0,1.0,Urban,N
77,Yes,1000,3022.000000,110.0,360.0,1.0,Urban,N
78,No,3167,4000.000000,180.0,300.0,0.0,Semiurban,N
79,Yes,3333,2166.000000,130.0,360.0,NaN,Semiurban,Y
80,No,3846,0.000000,111.0,360.0,1.0,Semiurban,Y
81,Yes,2395,0.000000,NaN,360.0,1.0,Semiurban,Y
82,No,1378,1881.000000,167.0,360.0,1.0,Urban,N
83,No,6000,2250.000000,265.0,360.0,NaN,Semiurban,N
84,No,3988,0.000000,50.0,240.0,1.0,Urban,Y
85,No,2366,2531.000000,136.0,360.0,1.0,Semiurban,Y
86,No,3333,2000.000000,99.0,360.0,NaN,Semiurban,Y
87,No,2500,2118.000000,104.0,360.0,1.0,Semiurban,Y
88,No,8566,0.000000,210.0,360.0,1.0,Urban,Y
89,No,5695,4167.000000,175.0,360.0,1.0,Semiurban,Y
90,No,2958,2900.000000,131.0,360.0,1.0,Semiurban,Y
91,No,6250,5654.000000,188.0,180.0,1.0,Semiurban,Y
92,No,3273,1820.000000,81.0,360.0,1.0,Urban,Y
93,No,4133,0.000000,122.0,360.0,1.0,Semiurban,Y
94,No,3620,0.000000,25.0,120.0,1.0,Semiurban,Y
95,NaN,6782,0.000000,NaN,360.0,NaN,Urban,N
96,No,2484,2302.000000,137.0,360.0,1.0,Semiurban,Y
97,No,1977,997.000000,50.0,360.0,1.0,Semiurban,Y
98,No,4188,0.000000,115.0,180.0,1.0,Semiurban,Y
99,No,1759,3541.000000,131.0,360.0,1.0,Semiurban,Y
100,No,4288,3263.000000,133.0,180.0,1.0,Urban,Y
101,No,4843,3806.000000,151.0,360.0,1.0,Semiurban,Y
102,No,13650,0.000000,NaN,360.0,1.0,Urban,Y
103,No,4652,3583.000000,NaN,360.0,1.0,Semiurban,Y
104,No,3816,754.000000,160.0,360.0,1.0,Urban,Y
105,No,3052,1030.000000,100.0,360.0,1.0,Urban,Y
106,No,11417,1126.000000,225.0,360.0,1.0,Urban,Y
107,NaN,7333,0.000000,120.0,360.0,1.0,Rural,N
108,No,3800,3600.000000,216.0,360.0,0.0,Urban,N
109,No,2071,754.000000,94.0,480.0,1.0,Semiurban,Y
110,No,5316,0.000000,136.0,360.0,1.0,Urban,Y
111,NaN,2929,2333.000000,139.0,360.0,1.0,Semiurban,Y
112,No,3572,4114.000000,152.0,NaN,0.0,Rural,N
113,Yes,7451,0.000000,NaN,360.0,1.0,Semiurban,Y
114,NaN,5050,0.000000,118.0,360.0,1.0,Semiurban,Y
115,No,14583,0.000000,185.0,180.0,1.0,Rural,Y
116,No,3167,2283.000000,154.0,360.0,1.0,Semiurban,Y
117,No,2214,1398.000000,85.0,360.0,NaN,Urban,Y
118,No,5568,2142.000000,175.0,360.0,1.0,Rural,N
119,No,10408,0.000000,259.0,360.0,1.0,Urban,Y
120,No,5667,2667.000000,180.0,360.0,1.0,Rural,Y
121,No,4166,0.000000,44.0,360.0,1.0,Semiurban,Y
122,No,2137,8980.000000,137.0,360.0,0.0,Semiurban,Y
123,No,2957,0.000000,81.0,360.0,1.0,Semiurban,Y
124,No,4300,2014.000000,194.0,360.0,1.0,Rural,Y
125,No,3692,0.000000,93.0,360.0,NaN,Rural,Y
126,No,23803,0.000000,370.0,360.0,1.0,Rural,Y
127,No,3865,1640.000000,NaN,360.0,1.0,Rural,Y
128,Yes,10513,3850.000000,160.0,180.0,0.0,Urban,N
129,No,6080,2569.000000,182.0,360.0,NaN,Rural,N
130,Yes,20166,0.000000,650.0,480.0,NaN,Urban,Y
131,No,2014,1929.000000,74.0,360.0,1.0,Urban,Y
132,No,2718,0.000000,70.0,360.0,1.0,Semiurban,Y
133,Yes,3459,0.000000,25.0,120.0,1.0,Semiurban,Y
134,No,4895,0.000000,102.0,360.0,1.0,Semiurban,Y
135,No,4000,7750.000000,290.0,360.0,1.0,Semiurban,N
136,No,4583,0.000000,84.0,360.0,1.0,Rural,N
137,Yes,3316,3500.000000,88.0,360.0,1.0,Urban,Y
138,No,14999,0.000000,242.0,360.0,0.0,Semiurban,N
139,No,4200,1430.000000,129.0,360.0,1.0,Rural,N
140,No,5042,2083.000000,185.0,360.0,1.0,Rural,N
141,No,5417,0.000000,168.0,360.0,1.0,Urban,Y
142,Yes,6950,0.000000,175.0,180.0,1.0,Semiurban,Y
143,No,2698,2034.000000,122.0,360.0,1.0,Semiurban,Y
144,No,11757,0.000000,187.0,180.0,1.0,Urban,Y
145,No,2330,4486.000000,100.0,360.0,1.0,Semiurban,Y
146,No,14866,0.000000,70.0,360.0,1.0,Urban,Y
147,No,1538,1425.000000,30.0,360.0,1.0,Urban,Y
148,No,10000,1666.000000,225.0,360.0,1.0,Rural,N
149,No,4860,830.000000,125.0,360.0,1.0,Semiurban,Y
150,No,6277,0.000000,118.0,360.0,0.0,Rural,N
151,Yes,2577,3750.000000,152.0,360.0,1.0,Rural,Y
152,No,9166,0.000000,244.0,360.0,1.0,Urban,N
153,No,2281,0.000000,113.0,360.0,1.0,Rural,N
154,No,3254,0.000000,50.0,360.0,1.0,Urban,Y
155,No,39999,0.000000,600.0,180.0,0.0,Semiurban,Y
156,No,6000,0.000000,160.0,360.0,NaN,Rural,Y
157,No,9538,0.000000,187.0,360.0,1.0,Urban,Y
158,NaN,2980,2083.000000,120.0,360.0,1.0,Rural,Y
159,No,4583,5625.000000,255.0,360.0,1.0,Semiurban,Y
160,No,1863,1041.000000,98.0,360.0,1.0,Semiurban,Y
161,No,7933,0.000000,275.0,360.0,1.0,Urban,N
162,No,3089,1280.000000,121.0,360.0,0.0,Semiurban,N
163,No,4167,1447.000000,158.0,360.0,1.0,Rural,Y
164,No,9323,0.000000,75.0,180.0,1.0,Urban,Y
165,No,3707,3166.000000,182.0,NaN,1.0,Rural,Y
166,No,4583,0.000000,112.0,360.0,1.0,Rural,N
167,No,2439,3333.000000,129.0,360.0,1.0,Rural,Y
168,No,2237,0.000000,63.0,480.0,0.0,Semiurban,N
169,No,8000,0.000000,200.0,360.0,1.0,Semiurban,Y
170,NaN,1820,1769.000000,95.0,360.0,1.0,Rural,Y
171,No,51763,0.000000,700.0,300.0,1.0,Urban,Y
172,No,3522,0.000000,81.0,180.0,1.0,Rural,N
173,No,5708,5625.000000,187.0,360.0,1.0,Semiurban,Y
174,Yes,4344,736.000000,87.0,360.0,1.0,Semiurban,N
175,No,3497,1964.000000,116.0,360.0,1.0,Rural,Y
176,No,2045,1619.000000,101.0,360.0,1.0,Rural,Y
177,No,5516,11300.000000,495.0,360.0,0.0,Semiurban,N
178,No,3750,0.000000,116.0,360.0,1.0,Semiurban,Y
179,No,2333,1451.000000,102.0,480.0,0.0,Urban,N
180,No,6400,7250.000000,180.0,360.0,0.0,Urban,N
181,No,1916,5063.000000,67.0,360.0,NaN,Rural,N
182,No,4600,0.000000,73.0,180.0,1.0,Semiurban,Y
183,No,33846,0.000000,260.0,360.0,1.0,Semiurban,N
184,No,3625,0.000000,108.0,360.0,1.0,Semiurban,Y
185,Yes,39147,4750.000000,120.0,360.0,1.0,Semiurban,Y
186,Yes,2178,0.000000,66.0,300.0,0.0,Rural,N
187,No,2383,2138.000000,58.0,360.0,NaN,Rural,Y
188,Yes,674,5296.000000,168.0,360.0,1.0,Rural,Y
189,No,9328,0.000000,188.0,180.0,1.0,Rural,Y
190,No,4885,0.000000,48.0,360.0,1.0,Rural,Y
191,No,12000,0.000000,164.0,360.0,1.0,Semiurban,N
192,No,6033,0.000000,160.0,360.0,1.0,Urban,N
193,No,3858,0.000000,76.0,360.0,1.0,Semiurban,Y
194,No,4191,0.000000,120.0,360.0,1.0,Rural,Y
195,No,3125,2583.000000,170.0,360.0,1.0,Semiurban,N
196,No,8333,3750.000000,187.0,360.0,1.0,Rural,Y
197,No,1907,2365.000000,120.0,NaN,1.0,Urban,Y
198,No,3416,2816.000000,113.0,360.0,NaN,Semiurban,Y
199,Yes,11000,0.000000,83.0,360.0,1.0,Urban,N
200,No,2600,2500.000000,90.0,360.0,1.0,Semiurban,Y
201,No,4923,0.000000,166.0,360.0,0.0,Semiurban,Y
202,No,3992,0.000000,NaN,180.0,1.0,Urban,N
203,No,3500,1083.000000,135.0,360.0,1.0,Urban,Y
204,No,3917,0.000000,124.0,360.0,1.0,Semiurban,Y
205,No,4408,0.000000,120.0,360.0,1.0,Semiurban,Y
206,No,3244,0.000000,80.0,360.0,1.0,Urban,Y
207,No,3975,2531.000000,55.0,360.0,1.0,Rural,Y
208,No,2479,0.000000,59.0,360.0,1.0,Urban,Y
209,No,3418,0.000000,127.0,360.0,1.0,Semiurban,N
210,No,10000,0.000000,214.0,360.0,1.0,Semiurban,N
211,No,3430,1250.000000,128.0,360.0,0.0,Semiurban,N
212,Yes,7787,0.000000,240.0,360.0,1.0,Urban,Y
213,Yes,5703,0.000000,130.0,360.0,1.0,Rural,Y
214,No,3173,3021.000000,137.0,360.0,1.0,Urban,Y
215,No,3850,983.000000,100.0,360.0,1.0,Semiurban,Y
216,No,150,1800.000000,135.0,360.0,1.0,Rural,N
217,No,3727,1775.000000,131.0,360.0,1.0,Semiurban,Y
218,NaN,5000,0.000000,72.0,360.0,0.0,Semiurban,N
219,No,4283,2383.000000,127.0,360.0,NaN,Semiurban,Y
220,No,2221,0.000000,60.0,360.0,0.0,Urban,N
221,No,4009,1717.000000,116.0,360.0,1.0,Semiurban,Y
222,No,2971,2791.000000,144.0,360.0,1.0,Semiurban,Y
223,No,7578,1010.000000,175.0,NaN,1.0,Semiurban,Y
224,No,6250,0.000000,128.0,360.0,1.0,Semiurban,Y
225,No,3250,0.000000,170.0,360.0,1.0,Rural,N
226,Yes,4735,0.000000,138.0,360.0,1.0,Urban,N
227,No,6250,1695.000000,210.0,360.0,1.0,Semiurban,Y
228,No,4758,0.000000,158.0,480.0,1.0,Semiurban,Y
229,Yes,6400,0.000000,200.0,360.0,1.0,Rural,Y
230,No,2491,2054.000000,104.0,360.0,1.0,Semiurban,Y
231,NaN,3716,0.000000,42.0,180.0,1.0,Rural,Y
232,No,3189,2598.000000,120.0,NaN,1.0,Rural,Y
233,No,8333,0.000000,280.0,360.0,1.0,Semiurban,Y
234,No,3155,1779.000000,140.0,360.0,1.0,Semiurban,Y
235,No,5500,1260.000000,170.0,360.0,1.0,Rural,Y
236,NaN,5746,0.000000,255.0,360.0,NaN,Urban,N
237,Yes,3463,0.000000,122.0,360.0,NaN,Urban,Y
238,No,3812,0.000000,112.0,360.0,1.0,Rural,Y
239,No,3315,0.000000,96.0,360.0,1.0,Semiurban,Y
240,No,5819,5000.000000,120.0,360.0,1.0,Rural,Y
241,No,2510,1983.000000,140.0,180.0,1.0,Urban,N
242,No,2965,5701.000000,155.0,60.0,1.0,Urban,Y
243,Yes,6250,1300.000000,108.0,360.0,1.0,Rural,Y
244,No,3406,4417.000000,123.0,360.0,1.0,Semiurban,Y
245,Yes,6050,4333.000000,120.0,180.0,1.0,Urban,N
246,No,9703,0.000000,112.0,360.0,1.0,Urban,Y
247,No,6608,0.000000,137.0,180.0,1.0,Urban,Y
248,No,2882,1843.000000,123.0,480.0,1.0,Semiurban,Y
249,No,1809,1868.000000,90.0,360.0,1.0,Urban,Y
250,No,1668,3890.000000,201.0,360.0,0.0,Semiurban,N
251,No,3427,0.000000,138.0,360.0,1.0,Urban,N
252,Yes,2583,2167.000000,104.0,360.0,1.0,Rural,Y
253,No,2661,7101.000000,279.0,180.0,1.0,Semiurban,Y
254,Yes,16250,0.000000,192.0,360.0,0.0,Urban,N
255,No,3083,0.000000,255.0,360.0,1.0,Rural,Y
256,No,6045,0.000000,115.0,360.0,0.0,Rural,N
257,No,5250,0.000000,94.0,360.0,1.0,Urban,N
258,No,14683,2100.000000,304.0,360.0,1.0,Rural,N
259,No,4931,0.000000,128.0,360.0,NaN,Semiurban,N
260,No,6083,4250.000000,330.0,360.0,NaN,Urban,Y
261,No,2060,2209.000000,134.0,360.0,1.0,Semiurban,Y
262,No,3481,0.000000,155.0,36.0,1.0,Semiurban,N
263,No,7200,0.000000,120.0,360.0,1.0,Rural,Y
264,Yes,5166,0.000000,128.0,360.0,1.0,Semiurban,Y
265,No,4095,3447.000000,151.0,360.0,1.0,Rural,Y
266,No,4708,1387.000000,150.0,360.0,1.0,Semiurban,Y
267,No,4333,1811.000000,160.0,360.0,0.0,Urban,Y
268,NaN,3418,0.000000,135.0,360.0,1.0,Rural,N
269,No,2876,1560.000000,90.0,360.0,1.0,Urban,Y
270,No,3237,0.000000,30.0,360.0,1.0,Urban,Y
271,No,11146,0.000000,136.0,360.0,1.0,Urban,Y
272,No,2833,1857.000000,126.0,360.0,1.0,Rural,Y
273,No,2620,2223.000000,150.0,360.0,1.0,Semiurban,Y
274,No,3900,0.000000,90.0,360.0,1.0,Semiurban,Y
275,No,2750,1842.000000,115.0,360.0,1.0,Semiurban,Y
276,No,3993,3274.000000,207.0,360.0,1.0,Semiurban,Y
277,No,3103,1300.000000,80.0,360.0,1.0,Urban,Y
278,No,14583,0.000000,436.0,360.0,1.0,Semiurban,Y
279,No,4100,0.000000,124.0,360.0,NaN,Rural,Y
280,Yes,4053,2426.000000,158.0,360.0,0.0,Urban,N
281,No,3927,800.000000,112.0,360.0,1.0,Semiurban,Y
282,No,2301,985.799988,78.0,180.0,1.0,Urban,Y
283,No,1811,1666.000000,54.0,360.0,1.0,Urban,Y
284,No,20667,0.000000,NaN,360.0,1.0,Rural,N
285,No,3158,3053.000000,89.0,360.0,1.0,Rural,Y
286,Yes,2600,1717.000000,99.0,300.0,1.0,Semiurban,N
287,No,3704,2000.000000,120.0,360.0,1.0,Rural,Y
288,No,4124,0.000000,115.0,360.0,1.0,Semiurban,Y
289,No,9508,0.000000,187.0,360.0,1.0,Rural,Y
290,No,3075,2416.000000,139.0,360.0,1.0,Rural,Y
291,No,4400,0.000000,127.0,360.0,0.0,Semiurban,N
292,No,3153,1560.000000,134.0,360.0,1.0,Urban,Y
293,No,5417,0.000000,143.0,480.0,0.0,Urban,N
294,No,2383,3334.000000,172.0,360.0,1.0,Semiurban,Y
295,NaN,4416,1250.000000,110.0,360.0,1.0,Urban,Y
296,No,6875,0.000000,200.0,360.0,1.0,Semiurban,Y
297,No,4666,0.000000,135.0,360.0,1.0,Urban,Y
298,No,5000,2541.000000,151.0,480.0,1.0,Rural,N
299,No,2014,2925.000000,113.0,360.0,1.0,Urban,N
300,No,1800,2934.000000,93.0,360.0,0.0,Urban,N
301,No,2875,1750.000000,105.0,360.0,1.0,Semiurban,Y
302,No,5000,0.000000,132.0,360.0,1.0,Rural,Y
303,No,1625,1803.000000,96.0,360.0,1.0,Urban,Y
304,No,4000,2500.000000,140.0,360.0,1.0,Rural,Y
305,No,2000,0.000000,NaN,360.0,1.0,Urban,N
306,No,3762,1666.000000,135.0,360.0,1.0,Rural,Y
307,No,2400,1863.000000,104.0,360.0,0.0,Urban,N
308,No,20233,0.000000,480.0,360.0,1.0,Rural,N
309,No,7667,0.000000,185.0,360.0,NaN,Rural,Y
310,No,2917,0.000000,84.0,360.0,1.0,Semiurban,Y
311,No,2927,2405.000000,111.0,360.0,1.0,Semiurban,Y
312,No,2507,0.000000,56.0,360.0,1.0,Rural,Y
313,Yes,5746,0.000000,144.0,84.0,NaN,Rural,Y
314,No,2473,1843.000000,159.0,360.0,1.0,Rural,N
315,No,3399,1640.000000,111.0,180.0,1.0,Urban,Y
316,No,3717,0.000000,120.0,360.0,1.0,Semiurban,Y
317,No,2058,2134.000000,88.0,360.0,NaN,Urban,Y
318,No,3541,0.000000,112.0,360.0,NaN,Semiurban,Y
319,Yes,10000,0.000000,155.0,360.0,1.0,Rural,N
320,No,2400,2167.000000,115.0,360.0,1.0,Semiurban,Y
321,No,4342,189.000000,124.0,360.0,1.0,Semiurban,Y
322,No,3601,1590.000000,NaN,360.0,1.0,Rural,Y
323,No,3166,2985.000000,132.0,360.0,NaN,Rural,Y
324,No,15000,0.000000,300.0,360.0,1.0,Rural,Y
325,Yes,8666,4983.000000,376.0,360.0,0.0,Rural,N
326,No,4917,0.000000,130.0,360.0,0.0,Rural,Y
327,Yes,5818,2160.000000,184.0,360.0,1.0,Semiurban,Y
328,No,4333,2451.000000,110.0,360.0,1.0,Urban,N
329,No,2500,0.000000,67.0,360.0,1.0,Urban,Y
330,No,4384,1793.000000,117.0,360.0,1.0,Urban,Y
331,No,2935,0.000000,98.0,360.0,1.0,Semiurban,Y
332,No,2833,0.000000,71.0,360.0,1.0,Urban,Y
333,NaN,63337,0.000000,490.0,180.0,1.0,Urban,Y
334,Yes,9833,1833.000000,182.0,180.0,1.0,Urban,Y
335,Yes,5503,4490.000000,70.0,NaN,1.0,Semiurban,Y
336,NaN,5250,688.000000,160.0,360.0,1.0,Rural,Y
337,Yes,2500,4600.000000,176.0,360.0,1.0,Rural,Y
338,No,1830,0.000000,NaN,360.0,0.0,Urban,N
339,No,4160,0.000000,71.0,360.0,1.0,Semiurban,Y
340,No,2647,1587.000000,173.0,360.0,1.0,Rural,N
341,No,2378,0.000000,46.0,360.0,1.0,Rural,N
342,No,4554,1229.000000,158.0,360.0,1.0,Urban,Y
343,No,3173,0.000000,74.0,360.0,1.0,Semiurban,Y
344,NaN,2583,2330.000000,125.0,360.0,1.0,Rural,Y
345,No,2499,2458.000000,160.0,360.0,1.0,Semiurban,Y
346,No,3523,3230.000000,152.0,360.0,0.0,Rural,N
347,No,3083,2168.000000,126.0,360.0,1.0,Urban,Y
348,No,6333,4583.000000,259.0,360.0,NaN,Semiurban,Y
349,No,2625,6250.000000,187.0,360.0,1.0,Rural,Y
350,No,9083,0.000000,228.0,360.0,1.0,Semiurban,Y
351,No,8750,4167.000000,308.0,360.0,1.0,Rural,N
352,No,2666,2083.000000,95.0,360.0,1.0,Rural,Y
353,Yes,5500,0.000000,105.0,360.0,0.0,Rural,N
354,No,2423,505.000000,130.0,360.0,1.0,Semiurban,Y
355,No,3813,0.000000,116.0,180.0,1.0,Urban,Y
356,No,8333,3167.000000,165.0,360.0,1.0,Rural,Y
357,No,3875,0.000000,67.0,360.0,1.0,Urban,N
358,No,3000,1666.000000,100.0,480.0,0.0,Urban,N
359,No,5167,3167.000000,200.0,360.0,1.0,Semiurban,Y
360,No,4723,0.000000,81.0,360.0,1.0,Semiurban,N
361,No,5000,3667.000000,236.0,360.0,1.0,Semiurban,Y
362,No,4750,2333.000000,130.0,360.0,1.0,Urban,Y
363,No,3013,3033.000000,95.0,300.0,NaN,Urban,Y
364,Yes,6822,0.000000,141.0,360.0,1.0,Rural,Y
365,No,6216,0.000000,133.0,360.0,1.0,Rural,N
366,No,2500,0.000000,96.0,480.0,1.0,Semiurban,N
367,No,5124,0.000000,124.0,NaN,0.0,Rural,N
368,No,6325,0.000000,175.0,360.0,1.0,Semiurban,Y
369,No,19730,5266.000000,570.0,360.0,1.0,Rural,N
370,Yes,15759,0.000000,55.0,360.0,1.0,Semiurban,Y
371,No,5185,0.000000,155.0,360.0,1.0,Semiurban,Y
372,Yes,9323,7873.000000,380.0,300.0,1.0,Rural,Y
373,No,3062,1987.000000,111.0,180.0,0.0,Urban,N
374,NaN,2764,1459.000000,110.0,360.0,1.0,Urban,Y
375,No,4817,923.000000,120.0,180.0,1.0,Urban,Y
376,No,8750,4996.000000,130.0,360.0,1.0,Rural,Y
377,No,4310,0.000000,130.0,360.0,NaN,Semiurban,Y
378,No,3069,0.000000,71.0,480.0,1.0,Urban,N
379,No,5391,0.000000,130.0,360.0,1.0,Urban,Y
380,NaN,3333,2500.000000,128.0,360.0,1.0,Semiurban,Y
381,No,5941,4232.000000,296.0,360.0,1.0,Semiurban,Y
382,No,6000,0.000000,156.0,360.0,1.0,Urban,Y
383,Yes,7167,0.000000,128.0,360.0,1.0,Urban,Y
384,No,4566,0.000000,100.0,360.0,1.0,Urban,N
385,NaN,3667,0.000000,113.0,180.0,1.0,Urban,Y
386,No,2346,1600.000000,132.0,360.0,1.0,Semiurban,Y
387,No,3010,3136.000000,NaN,360.0,0.0,Urban,N
388,No,2333,2417.000000,136.0,360.0,1.0,Urban,Y
389,No,5488,0.000000,125.0,360.0,1.0,Rural,Y
390,No,9167,0.000000,185.0,360.0,1.0,Rural,Y
391,No,9504,0.000000,275.0,360.0,1.0,Rural,Y
392,No,2583,2115.000000,120.0,360.0,NaN,Urban,Y
393,No,1993,1625.000000,113.0,180.0,1.0,Semiurban,Y
394,No,3100,1400.000000,113.0,360.0,1.0,Urban,Y
395,No,3276,484.000000,135.0,360.0,NaN,Semiurban,Y
396,No,3180,0.000000,71.0,360.0,0.0,Urban,N
397,No,3033,1459.000000,95.0,360.0,1.0,Urban,Y
398,No,3902,1666.000000,109.0,360.0,1.0,Rural,Y
399,No,1500,1800.000000,103.0,360.0,0.0,Semiurban,N
400,No,2889,0.000000,45.0,180.0,0.0,Urban,N
401,No,2755,0.000000,65.0,300.0,1.0,Rural,N
402,No,2500,20000.000000,103.0,360.0,1.0,Semiurban,Y
403,No,1963,0.000000,53.0,360.0,1.0,Semiurban,Y
404,Yes,7441,0.000000,194.0,360.0,1.0,Rural,N
405,No,4547,0.000000,115.0,360.0,1.0,Semiurban,Y
406,No,2167,2400.000000,115.0,360.0,1.0,Urban,Y
407,No,2213,0.000000,66.0,360.0,1.0,Rural,Y
408,No,8300,0.000000,152.0,300.0,0.0,Semiurban,N
409,No,81000,0.000000,360.0,360.0,0.0,Rural,N
410,Yes,3867,0.000000,62.0,360.0,1.0,Semiurban,N
411,NaN,6256,0.000000,160.0,360.0,NaN,Urban,Y
412,No,6096,0.000000,218.0,360.0,0.0,Rural,N
413,No,2253,2033.000000,110.0,360.0,1.0,Rural,Y
414,No,2149,3237.000000,178.0,360.0,0.0,Semiurban,N
415,No,2995,0.000000,60.0,360.0,1.0,Urban,Y

In [213]:
df2 = cr.iloc[:,[-1,-2]]
df2

    Loan_Status Property_Area
0             Y         Urban
1             N         Rural
2             Y         Urban
3             Y         Urban
4             Y         Urban
5             Y         Urban
6             Y         Urban
7             N     Semiurban
8             Y         Urban
9             N     Semiurban
10            Y         Urban
11            Y         Urban
12            Y         Urban
13            N         Rural
14            Y         Urban
15            Y         Urban
16            Y         Urban
17            N         Urban
18            N         Rural
19            Y         Urban
20            N         Urban
21            Y         Urban
22            N     Semiurban
23            N         Rural
24            N     Semiurban
25            Y     Semiurban
26            Y     Semiurban
27            Y         Urban
28            N         Urban
29            Y     Semiurban
30            N         Urban
31            N         Urban
32            N         Rural
33            Y     Semiurban
34            N         Rural
35            Y         Urban
36            N         Urban
37            Y     Semiurban
38            Y         Urban
39            Y     Semiurban
40            N         Urban
41            Y         Urban
42            Y         Urban
43            Y     Semiurban
44            Y         Urban
45            Y         Urban
46            Y         Urban
47            Y         Urban
48            N         Urban
49            Y     Semiurban
50            Y     Semiurban
51            Y     Semiurban
52            N     Semiurban
53            N         Urban
54            N         Urban
55            Y     Semiurban
56            Y     Semiurban
57            N         Rural
58            Y         Urban
59            Y         Urban
60            Y         Urban
61            Y         Urban
62            N         Rural
63            N         Rural
64            N     Semiurban
65            N     Semiurban
66            N         Urban
67            Y         Urban
68            Y         Urban
69            N     Semiurban
70            Y         Urban
71            Y     Semiurban
72            Y     Semiurban
73            N     Semiurban
74            Y     Semiurban
75            N         Urban
76            N         Urban
77            N         Urban
78            N     Semiurban
79            Y     Semiurban
80            Y     Semiurban
81            Y     Semiurban
82            N         Urban
83            N     Semiurban
84            Y         Urban
85            Y     Semiurban
86            Y     Semiurban
87            Y     Semiurban
88            Y         Urban
89            Y     Semiurban
90            Y     Semiurban
91            Y     Semiurban
92            Y         Urban
93            Y     Semiurban
94            Y     Semiurban
95            N         Urban
96            Y     Semiurban
97            Y     Semiurban
98            Y     Semiurban
99            Y     Semiurban
100           Y         Urban
101           Y     Semiurban
102           Y         Urban
103           Y     Semiurban
104           Y         Urban
105           Y         Urban
106           Y         Urban
107           N         Rural
108           N         Urban
109           Y     Semiurban
110           Y         Urban
111           Y     Semiurban
112           N         Rural
113           Y     Semiurban
114           Y     Semiurban
115           Y         Rural
116           Y     Semiurban
117           Y         Urban
118           N         Rural
119           Y         Urban
120           Y         Rural
121           Y     Semiurban
122           Y     Semiurban
123           Y     Semiurban
124           Y         Rural
125           Y         Rural
126           Y         Rural
127           Y         Rural
128           N         Urban
129           N         Rural
130           Y         Urban
131           Y         Urban
132           Y     Semiurban
133           Y     Semiurban
134           Y     Semiurban
135           N     Semiurban
136           N         Rural
137           Y         Urban
138           N     Semiurban
139           N         Rural
140           N         Rural
141           Y         Urban
142           Y     Semiurban
143           Y     Semiurban
144           Y         Urban
145           Y     Semiurban
146           Y         Urban
147           Y         Urban
148           N         Rural
149           Y     Semiurban
150           N         Rural
151           Y         Rural
152           N         Urban
153           N         Rural
154           Y         Urban
155           Y     Semiurban
156           Y         Rural
157           Y         Urban
158           Y         Rural
159           Y     Semiurban
160           Y     Semiurban
161           N         Urban
162           N     Semiurban
163           Y         Rural
164           Y         Urban
165           Y         Rural
166           N         Rural
167           Y         Rural
168           N     Semiurban
169           Y     Semiurban
170           Y         Rural
171           Y         Urban
172           N         Rural
173           Y     Semiurban
174           N     Semiurban
175           Y         Rural
176           Y         Rural
177           N     Semiurban
178           Y     Semiurban
179           N         Urban
180           N         Urban
181           N         Rural
182           Y     Semiurban
183           N     Semiurban
184           Y     Semiurban
185           Y     Semiurban
186           N         Rural
187           Y         Rural
188           Y         Rural
189           Y         Rural
190           Y         Rural
191           N     Semiurban
192           N         Urban
193           Y     Semiurban
194           Y         Rural
195           N     Semiurban
196           Y         Rural
197           Y         Urban
198           Y     Semiurban
199           N         Urban
200           Y     Semiurban
201           Y     Semiurban
202           N         Urban
203           Y         Urban
204           Y     Semiurban
205           Y     Semiurban
206           Y         Urban
207           Y         Rural
208           Y         Urban
209           N     Semiurban
210           N     Semiurban
211           N     Semiurban
212           Y         Urban
213           Y         Rural
214           Y         Urban
215           Y     Semiurban
216           N         Rural
217           Y     Semiurban
218           N     Semiurban
219           Y     Semiurban
220           N         Urban
221           Y     Semiurban
222           Y     Semiurban
223           Y     Semiurban
224           Y     Semiurban
225           N         Rural
226           N         Urban
227           Y     Semiurban
228           Y     Semiurban
229           Y         Rural
230           Y     Semiurban
231           Y         Rural
232           Y         Rural
233           Y     Semiurban
234           Y     Semiurban
235           Y         Rural
236           N         Urban
237           Y         Urban
238           Y         Rural
239           Y     Semiurban
240           Y         Rural
241           N         Urban
242           Y         Urban
243           Y         Rural
244           Y     Semiurban
245           N         Urban
246           Y         Urban
247           Y         Urban
248           Y     Semiurban
249           Y         Urban
250           N     Semiurban
251           N         Urban
252           Y         Rural
253           Y     Semiurban
254           N         Urban
255           Y         Rural
256           N         Rural
257           N         Urban
258           N         Rural
259           N     Semiurban
260           Y         Urban
261           Y     Semiurban
262           N     Semiurban
263           Y         Rural
264           Y     Semiurban
265           Y         Rural
266           Y     Semiurban
267           Y         Urban
268           N         Rural
269           Y         Urban
270           Y         Urban
271           Y         Urban
272           Y         Rural
273           Y     Semiurban
274           Y     Semiurban
275           Y     Semiurban
276           Y     Semiurban
277           Y         Urban
278           Y     Semiurban
279           Y         Rural
280           N         Urban
281           Y     Semiurban
282           Y         Urban
283           Y         Urban
284           N         Rural
285           Y         Rural
286           N     Semiurban
287           Y         Rural
288           Y     Semiurban
289           Y         Rural
290           Y         Rural
291           N     Semiurban
292           Y         Urban
293           N         Urban
294           Y     Semiurban
295           Y         Urban
296           Y     Semiurban
297           Y         Urban
298           N         Rural
299           N         Urban
300           N         Urban
301           Y     Semiurban
302           Y         Rural
303           Y         Urban
304           Y         Rural
305           N         Urban
306           Y         Rural
307           N         Urban
308           N         Rural
309           Y         Rural
310           Y     Semiurban
311           Y     Semiurban
312           Y         Rural
313           Y         Rural
314           N         Rural
315           Y         Urban
316           Y     Semiurban
317           Y         Urban
318           Y     Semiurban
319           N         Rural
320           Y     Semiurban
321           Y     Semiurban
322           Y         Rural
323           Y         Rural
324           Y         Rural
325           N         Rural
326           Y         Rural
327           Y     Semiurban
328           N         Urban
329           Y         Urban
330           Y         Urban
331           Y     Semiurban
332           Y         Urban
333           Y         Urban
334           Y         Urban
335           Y     Semiurban
336           Y         Rural
337           Y         Rural
338           N         Urban
339           Y     Semiurban
340           N         Rural
341           N         Rural
342           Y         Urban
343           Y     Semiurban
344           Y         Rural
345           Y     Semiurban
346           N         Rural
347           Y         Urban
348           Y     Semiurban
349           Y         Rural
350           Y     Semiurban
351           N         Rural
352           Y         Rural
353           N         Rural
354           Y     Semiurban
355           Y         Urban
356           Y         Rural
357           N         Urban
358           N         Urban
359           Y     Semiurban
360           N     Semiurban
361           Y     Semiurban
362           Y         Urban
363           Y         Urban
364           Y         Rural
365           N         Rural
366           N     Semiurban
367           N         Rural
368           Y     Semiurban
369           N         Rural
370           Y     Semiurban
371           Y     Semiurban
372           Y         Rural
373           N         Urban
374           Y         Urban
375           Y         Urban
376           Y         Rural
377           Y     Semiurban
378           N         Urban
379           Y         Urban
380           Y     Semiurban
381           Y     Semiurban
382           Y         Urban
383           Y         Urban
384           N         Urban
385           Y         Urban
386           Y     Semiurban
387           N         Urban
388           Y         Urban
389           Y         Rural
390           Y         Rural
391           Y         Rural
392           Y         Urban
393           Y     Semiurban
394           Y         Urban
395           Y     Semiurban
396           N         Urban
397           Y         Urban
398           Y         Rural
399           N     Semiurban
400           N         Urban
401           N         Rural
402           Y     Semiurban
403           Y     Semiurban
404           N         Rural
405           Y     Semiurban
406           Y         Urban
407           Y         Rural
408           N     Semiurban
409           N         Rural
410           N     Semiurban
411           Y         Urban
412           N         Rural
413           Y         Rural
414           N     Semiurban
415           Y         Urban
416           N         Urban
417           N         Urban
418           Y         Rural
419           Y     Semiurban
420           Y         Rural
421           N         Urban
422           Y         Urban
423           N         Urban
424           Y     Semiurban
425           Y         Rural
426           N         Rural
427           Y     Semiurban
428           Y         Rural
429           Y         Urban
430           Y     Semiurban
431           N         Rural
432           Y     Semiurban
433           Y     Semiurban
434           Y         Urban
435           Y     Semiurban
436           Y     Semiurban
437           Y         Urban
438           N         Urban
439           Y         Rural
440           Y     Semiurban
441           Y         Rural
442           Y     Semiurban
443           Y     Semiurban
444           Y         Rural
445           Y         Rural
446           Y         Rural
447           N         Rural
448           N         Rural
449           N     Semiurban
450           N         Rural
451           Y         Urban
452           N         Rural
453           Y         Rural
454           Y     Semiurban
455           Y     Semiurban
456           Y         Urban
457           N         Urban
458           Y         Rural
459           N     Semiurban
460           Y     Semiurban
461           Y         Urban
462           Y         Rural
463           Y     Semiurban
464           N     Semiurban
465           Y         Rural
466           N         Urban
467           Y     Semiurban
468           Y     Semiurban
469           N         Urban
470           Y     Semiurban
471           N         Rural
472           Y     Semiurban
473           Y         Urban
474           Y         Rural
475           Y         Rural
476           Y     Semiurban
477           N     Semiurban
478           Y     Semiurban
479           N         Urban
480           Y         Rural
481           Y         Rural
482           Y     Semiurban
483           Y     Semiurban
484           Y     Semiurban
485           Y         Rural
486           N         Rural
487           N         Urban
488           Y     Semiurban
489           N         Urban
490           Y     Semiurban
491           Y         Urban
492           Y         Rural
493           Y     Semiurban
494           N         Rural
495           Y     Semiurban
496           Y         Rural
497           Y         Urban
498           Y     Semiurban
499           N         Rural
500           Y         Rural
501           Y     Semiurban
502           Y     Semiurban
503           N         Rural
504           Y     Semiurban
505           Y         Rural
506           Y         Urban
507           N         Urban
508           Y         Urban
509           Y         Urban
510           N         Rural
511           Y     Semiurban
512           Y         Urban
513           N     Semiurban
514           N         Rural
515           Y         Rural
516           Y     Semiurban
517           N     Semiurban
518           N     Semiurban
519           N         Rural
520           Y     Semiurban
521           Y     Semiurban
522           Y         Rural
523           Y         Rural
524           N     Semiurban
525           Y         Rural
526           Y     Semiurban
527           Y     Semiurban
528           Y     Semiurban
529           Y     Semiurban
530           Y         Rural
531           Y         Urban
532           N         Rural
533           N     Semiurban
534           Y         Urban
535           Y         Rural
536           Y         Urban
537           Y     Semiurban
538           N         Rural
539           Y         Rural
540           Y     Semiurban
541           N     Semiurban
542           Y     Semiurban
543           Y         Urban
544           Y     Semiurban
545           Y         Rural
546           N     Semiurban
547           Y         Rural
548           N     Semiurban
549           Y         Rural
550           N         Rural
551           Y         Rural
552           Y         Urban
553           N         Urban
554           N         Rural
555           Y     Semiurban
556           Y         Urban
557           Y     Semiurban
558           Y     Semiurban
559           Y     Semiurban
560           Y     Semiurban
561           Y     Semiurban
562           Y         Rural
563           Y     Semiurban
564           N         Urban
565           Y         Rural
566           Y         Urban
567           N         Rural
568           N         Urban
569           N         Urban
570           Y         Urban
571           N         Urban
572           Y         Urban
573           N     Semiurban
574           N     Semiurban
575           Y         Urban
576           N     Semiurban
577           Y         Urban
578           Y         Rural
579           Y         Urban
580           Y     Semiurban
581           N         Urban
582           Y     Semiurban
583           N         Rural
584           N         Rural
585           N         Rural
586           Y         Urban
587           Y     Semiurban
588           Y     Semiurban
589           N     Semiurban
590           Y     Semiurban
591           N     Semiurban
592           Y     Semiurban
593           Y         Rural
594           Y         Urban
595           Y         Rural
596           N         Rural
597           N     Semiurban
598           Y         Rural
599           Y         Urban
600           N         Urban
601           Y         Rural
602           Y         Urban
603           Y         Rural
604           Y     Semiurban
605           N         Urban
606           Y     Semiurban
607           Y         Rural
608           Y         Rural
609           Y         Rural
610           Y         Rural
611           Y         Urban
612           Y         Urban
613           N     Semiurban
614           Y         Urban
615           Y         Urban
616           Y         Urban
617           Y         Urban
618           N         Urban
619           Y         Urban
620           Y     Semiurban
621           N         Rural
622           Y         Urban
623           Y     Semiurban
624           Y         Urban
625           Y     Semiurban
626           Y         Urban
627           N     Semiurban
628           Y     Semiurban
629           Y         Urban
630           Y         Urban
631           Y     Semiurban
632           Y         Urban
633           Y     Semiurban
634           Y         Urban
635           Y         Urban
636           Y         Urban
637           Y         Urban
638           Y         Urban
639           N         Rural
640           Y         Urban
641           Y         Urban
642           Y     Semiurban
643           Y         Urban
644           Y     Semiurban
645           Y         Urban
646           Y     Semiurban
647           Y         Urban
648           Y         Urban
649           N     Semiurban
650           Y         Urban
651           Y         Urban
652           Y         Urban
653           Y         Urban
654           Y         Urban
655           Y         Urban
656           Y     Semiurban
657           Y     Semiurban
658           Y         Urban
659           Y         Urban
660           Y         Urban
661           Y     Semiurban
662           Y         Urban
663           Y     Semiurban
664           Y         Urban

In [225]:
cr.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [235]:
cr.Self_Employed = cr.Self_Employed.replace({'Yes' : 1 , 'No' : 0})
cr.Married = cr.Married.replace({'Yes' : 1 , 'No' : 0})
cr.Loan_Status =  cr.Loan_Status.replace({'Y' : 1 , 'N' : 0})
cr.Education = cr.Education.replace({'Graduate' : 1 , 'Not Graduate' : 0})
cr.Gender = cr.Gender.replace({'Male' : 0 , 'Female' : 1})
cr.Property_Area = cr.Property_Area.replace({'Urban': 1 , 'Rural' : 0 , 'Semiurban': 2})

In [236]:
cr.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,0.0,0.0,0.0,1,0.0,5849,0.0,NaN,360.0,1.0,1,1
1,LP001003,0.0,1.0,1.0,1,0.0,4583,1508.0,128.0,360.0,1.0,0,0
2,LP001005,0.0,1.0,0.0,1,1.0,3000,0.0,66.0,360.0,1.0,1,1
3,LP001006,0.0,1.0,0.0,0,0.0,2583,2358.0,120.0,360.0,1.0,1,1
4,LP001008,0.0,0.0,0.0,1,0.0,6000,0.0,141.0,360.0,1.0,1,1

In [3]:
pa = pd.read_csv(r'D:Downloads/Datasets/Property_Price_Train.csv')

In [10]:
pa.isnull().sum()[pa.isnull().sum() > 0]

Series([], dtype: int64)

In [5]:
pa = pa.drop(['Lane_Type' , 'Fireplace_Quality' , 'Pool_Quality' , 'Fence_Quality' , 'Miscellaneous_Feature'], axis = 1)

In [6]:
pa.Lot_Extent = pa.Lot_Extent.fillna(pa.Lot_Extent.mean())
pa.Brick_Veneer_Type = pa.Brick_Veneer_Type.fillna('None')
pa.Brick_Veneer_Area = pa.Brick_Veneer_Area.fillna(pa.Brick_Veneer_Area.mean())
pa.Basement_Height = pa.Basement_Height.fillna('TA')
pa.Basement_Condition = pa.Basement_Condition.fillna('TA')
pa.Exposure_Level = pa.Exposure_Level.fillna('No')
pa.BsmtFinType1 = pa.BsmtFinType1.fillna('Unf')
pa.BsmtFinType2 = pa.BsmtFinType2.fillna('Unf')
pa.Electrical_System = pa.Electrical_System.fillna('SBrkr')
pa.Garage = pa.Garage.fillna('Attchd')
pa.Garage_Built_Year = pa.Garage_Built_Year.fillna(1980)
pa.Garage_Finish_Year = pa.Garage_Finish_Year.fillna('Unf')
pa.Garage_Quality = pa.Garage_Quality.fillna('TA')
pa.Garage_Condition = pa.Garage_Condition.fillna('TA')

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [11]:
pa.Zoning_Class = le.fit_transform(pa.Zoning_Class)
pa.Road_Type = le.fit_transform(pa.Road_Type)
pa.Property_Shape = le.fit_transform(pa.Property_Shape)
pa.Land_Outline = le.fit_transform(pa.Land_Outline)
pa.Utility_Type = le.fit_transform(pa.Utility_Type)
pa.Lot_Configuration = le.fit_transform(pa.Lot_Configuration)
pa.Property_Slope = le.fit_transform(pa.Property_Slope)
pa.Neighborhood  = le.fit_transform(pa.Neighborhood )
pa.Condition1 = le.fit_transform(pa.Condition1)
pa.Condition2 = le.fit_transform(pa.Condition2)
pa.House_Type = le.fit_transform(pa.House_Type)
pa.House_Design = le.fit_transform(pa.House_Design)
pa.Roof_Design = le.fit_transform(pa.Roof_Design)
pa.Roof_Quality = le.fit_transform(pa.Roof_Quality)
pa.Exterior1st = le.fit_transform(pa.Exterior1st)
pa.Exterior2nd = le.fit_transform(pa.Exterior2nd)
pa.Brick_Veneer_Type = le.fit_transform(pa.Brick_Veneer_Type)
pa.Exterior_Material = le.fit_transform(pa.Exterior_Material)
pa.Exterior_Condition = le.fit_transform(pa.Exterior_Condition)
pa.Foundation_Type = le.fit_transform(pa.Foundation_Type)
pa.Basement_Height = le.fit_transform(pa.Basement_Height)
pa.Basement_Condition = le.fit_transform(pa.Basement_Condition)
pa.Exposure_Level = le.fit_transform(pa.Exposure_Level)
pa.BsmtFinType1 = le.fit_transform(pa.BsmtFinType1)
pa.BsmtFinType2 = le.fit_transform(pa.BsmtFinType2)
pa.Heating_Type = le.fit_transform(pa.Heating_Type)
pa.Heating_Quality = le.fit_transform(pa.Heating_Quality)
pa.Air_Conditioning= le.fit_transform(pa.Air_Conditioning)
pa.Electrical_System = le.fit_transform(pa.Electrical_System)
pa.Kitchen_Quality= le.fit_transform(pa.Kitchen_Quality)
pa.Functional_Rate = le.fit_transform(pa.Functional_Rate)
pa.Garage = le.fit_transform(pa.Garage)
pa.Garage_Finish_Year = le.fit_transform(pa.Garage_Finish_Year)
pa.Garage_Quality = le.fit_transform(pa.Garage_Quality)
pa.Garage_Condition = le.fit_transform(pa.Garage_Condition)
pa.Pavedd_Drive = le.fit_transform(pa.Pavedd_Drive)
pa.Sale_Type = le.fit_transform(pa.Sale_Type)
pa.Sale_Condition = le.fit_transform(pa.Sale_Condition)

In [12]:
pa.head()

,Id,Building_Class,Zoning_Class,Lot_Extent,Lot_Size,Road_Type,Property_Shape,Land_Outline,Utility_Type,Lot_Configuration,Property_Slope,Neighborhood,Condition1,Condition2,House_Type,House_Design,Overall_Material,House_Condition,Construction_Year,Remodel_Year,Roof_Design,Roof_Quality,Exterior1st,Exterior2nd,Brick_Veneer_Type,Brick_Veneer_Area,Exterior_Material,Exterior_Condition,Foundation_Type,Basement_Height,Basement_Condition,Exposure_Level,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,Total_Basement_Area,Heating_Type,Heating_Quality,Air_Conditioning,Electrical_System,First_Floor_Area,Second_Floor_Area,LowQualFinSF,Grade_Living_Area,Underground_Full_Bathroom,Underground_Half_Bathroom,Full_Bathroom_Above_Grade,Half_Bathroom_Above_Grade,Bedroom_Above_Grade,Kitchen_Above_Grade,Kitchen_Quality,Rooms_Above_Grade,Functional_Rate,Fireplaces,Garage,Garage_Built_Year,Garage_Finish_Year,Garage_Size,Garage_Area,Garage_Quality,Garage_Condition,Pavedd_Drive,W_Deck_Area,Open_Lobby_Area,Enclosed_Lobby_Area,Three_Season_Lobby_Area,Screen_Lobby_Area,Pool_Area,Miscellaneous_Value,Month_Sold,Year_Sold,Sale_Type,Sale_Condition,Sale_Price
0,1,60,3,65.0,8450,1,3,3,0,4,0,5,2,2,0,5,7,5,2003,2003,1,4,12,13,1,196.0,2,4,2,2,3,3,2,706,5,0,150,856,1,0,1,4,856,854,0,1710,1,0,2,1,3,1,2,8,7,0,2,2003.0,1,2,1085.793744,4,4,2,163.788080,69.596115,20.337934,0,0,0,0,2,2008,8,4,208500
1,2,20,3,80.0,9600,1,3,3,0,2,0,24,1,2,0,2,6,8,1976,1976,1,4,8,8,2,0.0,3,4,1,2,3,1,0,978,5,0,284,1262,1,0,1,4,1262,0,0,1262,0,1,2,0,3,1,3,6,7,1,2,1976.0,1,2,196.316304,4,4,2,198.900074,74.716033,15.039392,0,0,0,0,5,2007,8,4,181500
2,3,60,3,68.0,11250,1,0,3,0,4,0,5,2,2,0,5,7,5,2001,2002,1,4,12,13,1,162.0,2,4,2,2,3,2,2,486,5,0,434,920,1,0,1,4,920,866,0,1786,1,0,2,1,3,1,2,6,7,1,2,2001.0,1,2,218.068403,4,4,2,26.127533,32.085268,-46.232198,0,0,0,0,9,2008,8,4,223500
3,4,70,3,60.0,9550,1,0,3,0,0,0,6,2,2,0,5,7,5,1915,1970,1,4,13,15,2,0.0,3,4,0,3,1,3,0,216,5,0,540,756,1,2,1,4,961,756,0,1717,1,0,1,0,3,1,2,7,7,1,6,1998.0,2,3,696.996439,4,4,2,46.948018,40.181415,60.921821,0,0,0,0,2,2006,8,0,140000
4,5,60,3,84.0,14260,1,0,3,0,2,0,15,2,2,0,5,8,5,2000,2000,1,4,12,13,1,350.0,2,4,2,2,3,0,2,655,5,0,490,1145,1,0,1,4,1145,1053,0,2198,1,0,2,1,4,1,2,9,7,1,2,2000.0,1,3,568.859882,4,4,2,-10.626105,20.755323,21.788818,0,0,0,0,12,2008,8,4,250000

In [13]:
df1 = pd.read_csv(r'D:Downloads/Datasets/Property_Price_Train.csv')

In [14]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 81 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Id                         1459 non-null   int64
 1   Building_Class             1459 non-null   int64
 2   Zoning_Class               1459 non-null   object
 3   Lot_Extent                 1200 non-null   float64
 4   Lot_Size                   1459 non-null   int64
 5   Road_Type                  1459 non-null   object
 6   Lane_Type                  91 non-null     object
 7   Property_Shape             1459 non-null   object
 8   Land_Outline               1459 non-null   object
 9   Utility_Type               1459 non-null   object
 10  Lot_Configuration          1459 non-null   object
 11  Property_Slope             1459 non-null   object
 12  Neighborhood               1459 non-null   object
 13  Condition1                 1459 non-null   object
 14  Condition2                 1459 non-null   object
 15  House_Type                 1459 non-null   object
 16  House_Design               1459 non-null   object
 17  Overall_Material           1459 non-null   int64
 18  House_Condition            1459 non-null   int64
 19  Construction_Year          1459 non-null   int64
 20  Remodel_Year               1459 non-null   int64
 21  Roof_Design                1459 non-null   object
 22  Roof_Quality               1459 non-null   object
 23  Exterior1st                1459 non-null   object
 24  Exterior2nd                1459 non-null   object
 25  Brick_Veneer_Type          1451 non-null   object
 26  Brick_Veneer_Area          1451 non-null   float64
 27  Exterior_Material          1459 non-null   object
 28  Exterior_Condition         1459 non-null   object
 29  Foundation_Type            1459 non-null   object
 30  Basement_Height            1422 non-null   object
 31  Basement_Condition         1422 non-null   object
 32  Exposure_Level             1421 non-null   object
 33  BsmtFinType1               1422 non-null   object
 34  BsmtFinSF1                 1459 non-null   int64
 35  BsmtFinType2               1421 non-null   object
 36  BsmtFinSF2                 1459 non-null   int64
 37  BsmtUnfSF                  1459 non-null   int64
 38  Total_Basement_Area        1459 non-null   int64
 39  Heating_Type               1459 non-null   object
 40  Heating_Quality            1459 non-null   object
 41  Air_Conditioning           1459 non-null   object
 42  Electrical_System          1458 non-null   object
 43  First_Floor_Area           1459 non-null   int64
 44  Second_Floor_Area          1459 non-null   int64
 45  LowQualFinSF               1459 non-null   int64
 46  Grade_Living_Area          1459 non-null   int64
 47  Underground_Full_Bathroom  1459 non-null   int64
 48  Underground_Half_Bathroom  1459 non-null   int64
 49  Full_Bathroom_Above_Grade  1459 non-null   int64
 50  Half_Bathroom_Above_Grade  1459 non-null   int64
 51  Bedroom_Above_Grade        1459 non-null   int64
 52  Kitchen_Above_Grade        1459 non-null   int64
 53  Kitchen_Quality            1459 non-null   object
 54  Rooms_Above_Grade          1459 non-null   int64
 55  Functional_Rate            1459 non-null   object
 56  Fireplaces                 1459 non-null   int64
 57  Fireplace_Quality          770 non-null    object
 58  Garage                     1378 non-null   object
 59  Garage_Built_Year          1378 non-null   float64
 60  Garage_Finish_Year         1378 non-null   object
 61  Garage_Size                1459 non-null   int64
 62  Garage_Area                1459 non-null   float64
 63  Garage_Quality             1378 non-null   object
 64  Garage_Condition           1378 non-null   object
 65  Pavedd_Drive               1459 non-null   object
 66  W_Deck_Area                1459 non-null   float64
 67  Open_Lobby_Area            1459 non-null   float64
 68  Enclosed_Lobby_Area        1459 non-null   float64
 69  Three_Season_Lobby_Area    1459 non-null   int64
 70  Screen_Lobby_Area          1459 non-null   int64
 71  Pool_Area                  1459 non-null   int64
 72  Pool_Quality               7 non-null      object
 73  Fence_Quality              281 non-null    object
 74  Miscellaneous_Feature      54 non-null     object
 75  Miscellaneous_Value        1459 non-null   int64
 76  Month_Sold                 1459 non-null   int64
 77  Year_Sold                  1459 non-null   int64
 78  Sale_Type                  1459 non-null   object
 79  Sale_Condition             1459 non-null   object
 80  Sale_Price                 1459 non-null   int64
dtypes: float64(7), int64(31), object(43)
memory usage: 923.4+ KB

In [24]:
df1 = df1.drop(['Lane_Type' , 'Fireplace_Quality' , 'Pool_Quality' , 'Fence_Quality' , 'Miscellaneous_Feature'], axis = 1)

In [33]:
df1.Lot_Extent = df1.Lot_Extent.fillna(pa.Lot_Extent.mean())
df1.Brick_Veneer_Type = df1.Brick_Veneer_Type.fillna('None')
df1.Brick_Veneer_Area = df1.Brick_Veneer_Area.fillna(pa.Brick_Veneer_Area.mean())
df1.Basement_Height = df1.Basement_Height.fillna('TA')
df1.Basement_Condition = df1.Basement_Condition.fillna('TA')
df1.Exposure_Level = df1.Exposure_Level.fillna('No')
df1.BsmtFinType1 = df1.BsmtFinType1.fillna('Unf')
df1.BsmtFinType2 = df1.BsmtFinType2.fillna('Unf')
df1.Electrical_System = df1.Electrical_System.fillna('SBrkr')
df1.Garage = df1.Garage.fillna('Attchd')
df1.Garage_Built_Year = df1.Garage_Built_Year.fillna(1980)
df1.Garage_Finish_Year = df1.Garage_Finish_Year.fillna('Unf')
df1.Garage_Quality = df1.Garage_Quality.fillna('TA')
df1.Garage_Condition = df1.Garage_Condition.fillna('TA')

In [15]:
df1.select_dtypes(include = ['object']).columns

Index(['Zoning_Class', 'Road_Type', 'Lane_Type', 'Property_Shape',
       'Land_Outline', 'Utility_Type', 'Lot_Configuration', 'Property_Slope',
       'Neighborhood', 'Condition1', 'Condition2', 'House_Type',
       'House_Design', 'Roof_Design', 'Roof_Quality', 'Exterior1st',
       'Exterior2nd', 'Brick_Veneer_Type', 'Exterior_Material',
       'Exterior_Condition', 'Foundation_Type', 'Basement_Height',
       'Basement_Condition', 'Exposure_Level', 'BsmtFinType1', 'BsmtFinType2',
       'Heating_Type', 'Heating_Quality', 'Air_Conditioning',
       'Electrical_System', 'Kitchen_Quality', 'Functional_Rate',
       'Fireplace_Quality', 'Garage', 'Garage_Finish_Year', 'Garage_Quality',
       'Garage_Condition', 'Pavedd_Drive', 'Pool_Quality', 'Fence_Quality',
       'Miscellaneous_Feature', 'Sale_Type', 'Sale_Condition'],
      dtype='object')

In [35]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()

In [36]:
df1[df1.select_dtypes(include = ['object']).columns] = df1[df1.select_dtypes(include = ['object']).columns].apply(le.fit_transform)

In [37]:
df1.head()

,Id,Building_Class,Zoning_Class,Lot_Extent,Lot_Size,Road_Type,Property_Shape,Land_Outline,Utility_Type,Lot_Configuration,Property_Slope,Neighborhood,Condition1,Condition2,House_Type,House_Design,Overall_Material,House_Condition,Construction_Year,Remodel_Year,Roof_Design,Roof_Quality,Exterior1st,Exterior2nd,Brick_Veneer_Type,Brick_Veneer_Area,Exterior_Material,Exterior_Condition,Foundation_Type,Basement_Height,Basement_Condition,Exposure_Level,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,Total_Basement_Area,Heating_Type,Heating_Quality,Air_Conditioning,Electrical_System,First_Floor_Area,Second_Floor_Area,LowQualFinSF,Grade_Living_Area,Underground_Full_Bathroom,Underground_Half_Bathroom,Full_Bathroom_Above_Grade,Half_Bathroom_Above_Grade,Bedroom_Above_Grade,Kitchen_Above_Grade,Kitchen_Quality,Rooms_Above_Grade,Functional_Rate,Fireplaces,Garage,Garage_Built_Year,Garage_Finish_Year,Garage_Size,Garage_Area,Garage_Quality,Garage_Condition,Pavedd_Drive,W_Deck_Area,Open_Lobby_Area,Enclosed_Lobby_Area,Three_Season_Lobby_Area,Screen_Lobby_Area,Pool_Area,Miscellaneous_Value,Month_Sold,Year_Sold,Sale_Type,Sale_Condition,Sale_Price
0,1,60,3,65.0,8450,1,3,3,0,4,0,5,2,2,0,5,7,5,2003,2003,1,4,12,13,1,196.0,2,4,2,2,3,3,2,706,5,0,150,856,1,0,1,4,856,854,0,1710,1,0,2,1,3,1,2,8,7,0,2,2003.0,1,2,1085.793744,4,4,2,163.788080,69.596115,20.337934,0,0,0,0,2,2008,8,4,208500
1,2,20,3,80.0,9600,1,3,3,0,2,0,24,1,2,0,2,6,8,1976,1976,1,4,8,8,2,0.0,3,4,1,2,3,1,0,978,5,0,284,1262,1,0,1,4,1262,0,0,1262,0,1,2,0,3,1,3,6,7,1,2,1976.0,1,2,196.316304,4,4,2,198.900074,74.716033,15.039392,0,0,0,0,5,2007,8,4,181500
2,3,60,3,68.0,11250,1,0,3,0,4,0,5,2,2,0,5,7,5,2001,2002,1,4,12,13,1,162.0,2,4,2,2,3,2,2,486,5,0,434,920,1,0,1,4,920,866,0,1786,1,0,2,1,3,1,2,6,7,1,2,2001.0,1,2,218.068403,4,4,2,26.127533,32.085268,-46.232198,0,0,0,0,9,2008,8,4,223500
3,4,70,3,60.0,9550,1,0,3,0,0,0,6,2,2,0,5,7,5,1915,1970,1,4,13,15,2,0.0,3,4,0,3,1,3,0,216,5,0,540,756,1,2,1,4,961,756,0,1717,1,0,1,0,3,1,2,7,7,1,6,1998.0,2,3,696.996439,4,4,2,46.948018,40.181415,60.921821,0,0,0,0,2,2006,8,0,140000
4,5,60,3,84.0,14260,1,0,3,0,2,0,15,2,2,0,5,8,5,2000,2000,1,4,12,13,1,350.0,2,4,2,2,3,0,2,655,5,0,490,1145,1,0,1,4,1145,1053,0,2198,1,0,2,1,4,1,2,9,7,1,2,2000.0,1,3,568.859882,4,4,2,-10.626105,20.755323,21.788818,0,0,0,0,12,2008,8,4,250000

In [ ]:
#DATA CLEANING

In [55]:
df2 = pd.read_csv(r'D:Downloads/Datasets/CreditRisk.csv')

In [56]:
df2.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [57]:
df2.Gender = df2.Gender.fillna("Male")
df2.Married = df2.Married.fillna("Yes")
df2.Dependents = df2.Dependents.fillna(2)
df2.Self_Employed = df2.Self_Employed.fillna("No")
df2.LoanAmount = df2.LoanAmount.fillna(df2.LoanAmount.mean())
df2.Loan_Amount_Term = df2.Loan_Amount_Term.fillna(360)
df2.Credit_History = df2.Credit_History.fillna(0)

In [63]:
df2 = df2.drop(['Loan_ID'] , axis = 1)

In [59]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [60]:
df2[df2.select_dtypes(include = ['object']).columns] = df2[df2.select_dtypes(include = ['object']).columns].apply(le.fit_transform)

In [64]:
df2.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,1,0,0.0,0,0,5849,0.0,142.51153,360.0,1.0,2,1
1,1,1,1.0,0,0,4583,1508.0,128.00000,360.0,1.0,0,0
2,1,1,0.0,0,1,3000,0.0,66.00000,360.0,1.0,2,1
3,1,1,0.0,1,0,2583,2358.0,120.00000,360.0,1.0,2,1
4,1,0,0.0,0,0,6000,0.0,141.00000,360.0,1.0,2,1

In [ ]:
# SAMPLING

In [65]:
from sklearn.model_selection import train_test_split

In [66]:
cr_train , cr_test = train_test_split(df2 , test_size = 0.2)

In [67]:
cr_train.shape

(784, 12)

In [68]:
cr_test.shape

(197, 12)

In [69]:
cr_train.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
75,1,0,0.0,0,0,3750,0.0,113.0,480.0,1.0,2,0
58,1,1,1.0,0,0,8080,2250.0,180.0,360.0,1.0,2,1
175,1,1,0.0,0,0,3497,1964.0,116.0,360.0,1.0,0,1
860,1,1,2.0,0,1,5000,2166.0,150.0,360.0,1.0,2,1
751,1,1,1.0,0,0,2014,2925.0,120.0,360.0,1.0,0,1

In [77]:
cr_test.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
106,1,1,2.0,0,0,11417,1126.0,225.0,360.0,1.0,2,1
896,0,0,0.0,0,0,5530,0.0,135.0,360.0,0.0,2,1
716,1,1,1.0,0,0,3901,0.0,116.0,360.0,1.0,2,1
355,0,0,2.0,0,0,3813,0.0,116.0,180.0,1.0,2,1
529,1,0,0.0,1,0,6783,0.0,130.0,360.0,1.0,1,1

In [70]:
cr_train_x = cr_train.iloc[: , 0 : -1]
cr_train_y = cr_train.iloc[ : , -1]

In [72]:
cr_train_x.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
75,1,0,0.0,0,0,3750,0.0,113.0,480.0,1.0,2
58,1,1,1.0,0,0,8080,2250.0,180.0,360.0,1.0,2
175,1,1,0.0,0,0,3497,1964.0,116.0,360.0,1.0,0
860,1,1,2.0,0,1,5000,2166.0,150.0,360.0,1.0,2
751,1,1,1.0,0,0,2014,2925.0,120.0,360.0,1.0,0

In [73]:
cr_train_y.head()

75     0
58     1
175    1
860    1
751    1
Name: Loan_Status, dtype: int32

In [78]:
cr_test_x = cr_test.iloc[: , 0 : -1]
cr_test_y = cr_test.iloc[ : , -1]

In [79]:
cr_test_x.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
106,1,1,2.0,0,0,11417,1126.0,225.0,360.0,1.0,2
896,0,0,0.0,0,0,5530,0.0,135.0,360.0,0.0,2
716,1,1,1.0,0,0,3901,0.0,116.0,360.0,1.0,2
355,0,0,2.0,0,0,3813,0.0,116.0,180.0,1.0,2
529,1,0,0.0,1,0,6783,0.0,130.0,360.0,1.0,1

In [80]:
cr_test_y.head()

106    1
896    1
716    1
355    1
529    1
Name: Loan_Status, dtype: int32

In [2]:
import pandas as pd

In [90]:
cred = pd.read_csv(r'D:Downloads/Datasets/CreditRisk.csv')

In [10]:
cred.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [2]:
cred.groupby(['Education']).ApplicantIncome.agg(['mean' , 'median' , 'max' , 'min' , 'count' , 'std']).round()

NameError: name 'cred' is not defined

In [1]:
cred.groupby([''])

NameError: name 'cred' is not defined

In [24]:
cred.groupby('Education').ApplicantIncome.median()

Education
Graduate        4000
Not Graduate    3333
Name: ApplicantIncome, dtype: int64

In [14]:
cred.sort_values('ApplicantIncome' , ascending = False)

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
409,Male,Yes,4.0,Graduate,No,81000,0.000000,360.00000,360.0,0.0,Rural,N
695,Male,Yes,4.0,Graduate,No,72529,0.000000,360.00000,360.0,1.0,Urban,Y
333,Male,Yes,0.0,Graduate,No,63337,0.000000,490.00000,180.0,1.0,Urban,Y
171,Male,Yes,4.0,Graduate,No,51763,0.000000,700.00000,300.0,1.0,Urban,Y
155,Male,Yes,4.0,Graduate,No,39999,0.000000,600.00000,180.0,0.0,Semiurban,Y
185,Male,Yes,0.0,Graduate,Yes,39147,4750.000000,120.00000,360.0,1.0,Semiurban,Y
443,Male,No,1.0,Graduate,No,37719,0.000000,152.00000,360.0,1.0,Semiurban,Y
183,Male,Yes,1.0,Graduate,No,33846,0.000000,260.00000,360.0,1.0,Semiurban,N
757,Male,Yes,0.0,Graduate,Yes,32000,0.000000,550.00000,360.0,0.0,Semiurban,Y
893,Male,No,0.0,Graduate,No,29167,0.000000,185.00000,360.0,1.0,Semiurban,Y
886,Male,No,1.0,Graduate,No,24797,0.000000,240.00000,360.0,1.0,Semiurban,Y
126,Male,Yes,4.0,Graduate,No,23803,0.000000,370.00000,360.0,1.0,Rural,Y
506,Male,Yes,0.0,Graduate,No,20833,6667.000000,480.00000,360.0,0.0,Urban,Y
284,Male,Yes,0.0,Graduate,No,20667,0.000000,142.51153,360.0,1.0,Rural,N
308,Male,No,0.0,Graduate,No,20233,0.000000,480.00000,360.0,1.0,Rural,N
130,Male,No,0.0,Graduate,Yes,20166,0.000000,650.00000,480.0,0.0,Urban,Y
369,Male,Yes,0.0,Graduate,No,19730,5266.000000,570.00000,360.0,1.0,Rural,N
561,Female,Yes,1.0,Graduate,Yes,19484,0.000000,600.00000,360.0,1.0,Semiurban,Y
877,Male,Yes,1.0,Graduate,No,18840,0.000000,234.00000,360.0,1.0,Rural,Y
487,Male,Yes,1.0,Graduate,No,18333,0.000000,500.00000,360.0,1.0,Urban,N
534,Female,No,0.0,Not Graduate,Yes,18165,0.000000,125.00000,360.0,1.0,Urban,Y
525,Male,Yes,2.0,Graduate,Yes,17500,0.000000,400.00000,360.0,1.0,Rural,Y
493,Female,No,0.0,Not Graduate,Yes,17263,0.000000,225.00000,360.0,1.0,Semiurban,Y
467,Male,Yes,0.0,Graduate,No,16692,0.000000,110.00000,360.0,1.0,Semiurban,Y
478,Male,Yes,1.0,Graduate,Yes,16667,2250.000000,86.00000,360.0,1.0,Semiurban,Y
572,Male,Yes,2.0,Graduate,No,16666,0.000000,275.00000,360.0,1.0,Urban,Y
475,Male,Yes,2.0,Graduate,Yes,16525,1014.000000,150.00000,360.0,1.0,Rural,Y
254,Male,No,0.0,Graduate,Yes,16250,0.000000,192.00000,360.0,0.0,Urban,N
594,Male,Yes,0.0,Graduate,Yes,16120,0.000000,260.00000,360.0,1.0,Urban,Y
937,Male,No,1.0,Graduate,No,16000,5000.000000,40.00000,360.0,1.0,Semiurban,Y
370,Female,No,0.0,Graduate,Yes,15759,0.000000,55.00000,360.0,1.0,Semiurban,Y
793,Male,Yes,4.0,Graduate,No,15312,0.000000,187.00000,360.0,0.0,Urban,Y
324,Male,Yes,4.0,Graduate,No,15000,0.000000,300.00000,360.0,1.0,Rural,Y
138,Male,No,0.0,Graduate,No,14999,0.000000,242.00000,360.0,0.0,Semiurban,N
916,Female,No,2.0,Graduate,Yes,14987,0.000000,177.00000,360.0,1.0,Rural,Y
844,Male,No,0.0,Graduate,No,14911,14507.000000,130.00000,360.0,1.0,Semiurban,Y
424,Male,Yes,0.0,Graduate,No,14880,0.000000,96.00000,360.0,1.0,Semiurban,Y
146,Female,Yes,2.0,Graduate,No,14866,0.000000,70.00000,360.0,1.0,Urban,Y
258,Male,Yes,0.0,Graduate,No,14683,2100.000000,304.00000,360.0,1.0,Rural,N
278,Male,Yes,0.0,Graduate,No,14583,0.000000,436.00000,360.0,1.0,Semiurban,Y
115,Male,Yes,1.0,Graduate,No,14583,0.000000,185.00000,180.0,1.0,Rural,Y
102,Male,Yes,2.0,Graduate,No,13650,0.000000,142.51153,360.0,1.0,Urban,Y
622,Male,Yes,2.0,Graduate,No,13633,0.000000,280.00000,240.0,1.0,Urban,Y
705,Male,Yes,4.0,Graduate,No,13518,0.000000,390.00000,360.0,1.0,Rural,Y
509,Female,No,1.0,Graduate,No,13262,0.000000,40.00000,360.0,1.0,Urban,Y
802,Male,Yes,0.0,Not Graduate,No,13083,0.000000,142.51153,360.0,1.0,Rural,Y
759,Female,No,0.0,Graduate,No,12941,0.000000,150.00000,300.0,1.0,Urban,Y
432,Male,No,0.0,Graduate,No,12876,0.000000,405.00000,360.0,1.0,Semiurban,Y
9,Male,Yes,1.0,Graduate,No,12841,10968.000000,349.00000,360.0,1.0,Semiurban,N
34,Male,No,4.0,Graduate,No,12500,3000.000000,320.00000,360.0,1.0,Rural,N
738,Female,No,0.0,Graduate,No,12500,0.000000,300.00000,360.0,0.0,Urban,N
627,Male,Yes,2.0,Graduate,No,12173,0.000000,166.00000,360.0,0.0,Semiurban,N
604,Female,Yes,1.0,Graduate,No,12000,0.000000,496.00000,360.0,1.0,Semiurban,Y
191,Male,No,0.0,Graduate,No,12000,0.000000,164.00000,360.0,1.0,Semiurban,N
144,Male,Yes,2.0,Graduate,No,11757,0.000000,187.00000,180.0,1.0,Urban,Y
54,Female,Yes,1.0,Graduate,Yes,11500,0.000000,286.00000,360.0,0.0,Urban,N
106,Male,Yes,2.0,Graduate,No,11417,1126.000000,225.00000,360.0,1.0,Urban,Y
533,Male,No,1.0,Graduate,No,11250,0.000000,196.00000,360.0,0.0,Semiurban,N
271,Male,Yes,0.0,Graduate,No,11146,0.000000,136.00000,360.0,1.0,Urban,Y
199,Male,No,0.0,Graduate,Yes,11000,0.000000,83.00000,360.0,1.0,Urban,N
758,Male,Yes,2.0,Graduate,Yes,10890,0.000000,260.00000,12.0,1.0,Rural,Y
483,Male,Yes,0.0,Graduate,No,10833,0.000000,234.00000,360.0,1.0,Semiurban,Y
67,Male,Yes,1.0,Graduate,No,10750,0.000000,312.00000,360.0,1.0,Urban,Y
128,Male,Yes,1.0,Graduate,Yes,10513,3850.000000,160.00000,180.0,0.0,Urban,N
438,Male,No,0.0,Graduate,Yes,10416,0.000000,187.00000,360.0,0.0,Urban,N
119,Female,No,0.0,Graduate,No,10408,0.000000,259.00000,360.0,1.0,Urban,Y
798,Male,Yes,4.0,Graduate,No,10166,750.000000,150.00000,360.0,1.0,Urban,Y
557,Male,Yes,4.0,Graduate,Yes,10139,0.000000,260.00000,360.0,1.0,Semiurban,Y
435,Female,Yes,2.0,Graduate,No,10047,0.000000,142.51153,240.0,1.0,Semiurban,Y
148,Female,No,0.0,Graduate,No,10000,1666.000000,225.00000,360.0,1.0,Rural,N
898,Female,Yes,2.0,Graduate,No,10000,11666.000000,460.00000,360.0,1.0,Urban,Y
861,Male,Yes,2.0,Graduate,No,10000,0.000000,142.51153,360.0,1.0,Urban,Y
210,Female,No,0.0,Graduate,No,10000,0.000000,214.00000,360.0,1.0,Semiurban,N
808,Male,Yes,1.0,Graduate,No,10000,2690.000000,412.00000,360.0,1.0,Semiurban,N
319,Male,Yes,1.0,Graduate,Yes,10000,0.000000,155.00000,360.0,1.0,Rural,N
598,Male,Yes,0.0,Graduate,Yes,9963,0.000000,180.00000,360.0,1.0,Rural,Y
334,Male,Yes,1.0,Graduate,Yes,9833,1833.000000,182.00000,180.0,1.0,Urban,Y
712,Male,Yes,4.0,Graduate,No,9719,0.000000,61.00000,360.0,1.0,Urban,Y
246,Male,Yes,2.0,Graduate,No,9703,0.000000,112.00000,360.0,1.0,Urban,Y
945,Male,Yes,4.0,Graduate,No,9699,0.000000,300.00000,360.0,1.0,Urban,Y
25,Male,Yes,0.0,Graduate,Yes,9560,0.000000,191.00000,360.0,1.0,Semiurban,Y
157,Male,Yes,1.0,Graduate,No,9538,0.000000,187.00000,360.0,1.0,Urban,Y
289,Male,No,0.0,Graduate,No,9508,0.000000,187.00000,360.0,1.0,Rural,Y
391,Male,Yes,4.0,Graduate,No,9504,0.000000,275.00000,360.0,1.0,Rural,Y
592,Male,No,4.0,Graduate,Yes,9357,0.000000,292.00000,360.0,1.0,Semiurban,Y
189,Male,Yes,0.0,Graduate,No,9328,0.000000,188.00000,180.0,1.0,Rural,Y
372,Male,Yes,2.0,Graduate,Yes,9323,7873.000000,380.00000,300.0,1.0,Rural,Y
164,Male,Yes,0.0,Graduate,No,9323,0.000000,75.00000,180.0,1.0,Urban,Y
632,Male,Yes,0.0,Graduate,No,9226,7916.000000,300.00000,360.0,1.0,Urban,Y
980,Male,No,0.0,Graduate,Yes,9200,0.000000,98.00000,180.0,1.0,Rural,Y
801,Male,Yes,2.0,Graduate,No,9167,0.000000,235.00000,360.0,1.0,Semiurban,Y
390,Male,No,4.0,Graduate,No,9167,0.000000,185.00000,360.0,1.0,Rural,Y
152,Male,No,0.0,Graduate,No,9166,0.000000,244.00000,360.0,1.0,Urban,N
350,Male,Yes,0.0,Graduate,No,9083,0.000000,228.00000,360.0,1.0,Semiurban,Y
897,Male,No,0.0,Not Graduate,No,9000,0.000000,122.00000,360.0,1.0,Rural,Y
564,Male,Yes,2.0,Graduate,No,8799,0.000000,258.00000,360.0,0.0,Urban,N
899,Male,Yes,1.0,Graduate,No,8750,0.000000,297.00000,360.0,1.0,Urban,Y
351,Male,No,0.0,Graduate,No,8750,4167.000000,308.00000,360.0,1.0,Rural,N
376,Male,Yes,4.0,Graduate,No,8750,4996.000000,130.00000,360.0,1.0,Rural,Y
814,Male,Yes,0.0,Graduate,Yes,8706,0.000000,108.00000,480.0,1.0,Rural,Y
761,Male,No,0.0,Not Graduate,Yes,8703,0.000000,199.00000,360.0,0.0,Rural,N
964,Male,Yes,2.0,Graduate,No,8667,0.000000,254.00000,360.0,1.0,Rural,Y
325,Male,Yes,1.0,Graduate,Yes,8666,4983.000000,376.00000,360.0,0.0,Rural,N
430,Female,No,1.0,Graduate,Yes,8624,0.000000,150.00000,360.0,1.0,Semiurban,Y
88,Male,No,0.0,Graduate,No,8566,0.000000,210.00000,360.0,1.0,Urban,Y
974,Female,Yes,0.0,Graduate,No,8550,4255.000000,96.00000,360.0,0.0,Urban,Y
697,Male,Yes,0.0,Graduate,No,8449,0.000000,257.00000,360.0,1.0,Rural,N
959,Male,Yes,4.0,Graduate,No,8334,0.000000,260.00000,360.0,1.0,Urban,Y
459,Male,Yes,0.0,Graduate,No,8334,0.000000,160.00000,360.0,1.0,Semiurban,N
233,Female,No,0.0,Graduate,No,8333,0.000000,280.00000,360.0,1.0,Semiurban,Y
196,Male,No,0.0,Graduate,No,8333,3750.000000,187.00000,360.0,1.0,Rural,Y
356,Male,Yes,2.0,Graduate,No,8333,3167.000000,165.00000,360.0,1.0,Rural,Y
484,Male,Yes,2.0,Graduate,No,8333,0.000000,246.00000,360.0,1.0,Semiurban,Y
903,Male,Yes,1.0,Graduate,No,8333,4000.000000,142.51153,360.0,1.0,Urban,Y
408,Male,Yes,1.0,Graduate,No,8300,0.000000,152.00000,300.0,0.0,Semiurban,N
58,Male,Yes,1.0,Graduate,No,8080,2250.000000,180.00000,360.0,1.0,Urban,Y
611,Male,Yes,1.0,Graduate,No,8072,240.000000,253.00000,360.0,1.0,Urban,Y
169,Male,Yes,2.0,Graduate,No,8000,0.000000,200.00000,360.0,1.0,Semiurban,Y
663,Male,Yes,4.0,Not Graduate,Yes,8000,250.000000,187.00000,360.0,1.0,Semiurban,Y
693,Female,Yes,0.0,Graduate,No,7950,0.000000,185.00000,360.0,1.0,Urban,Y
523,Male,Yes,2.0,Graduate,Yes,7948,7166.000000,480.00000,360.0,1.0,Rural,Y
161,Male,Yes,0.0,Graduate,No,7933,0.000000,275.00000,360.0,1.0,Urban,N
441,Male,Yes,0.0,Graduate,No,7901,1833.000000,180.00000,360.0,1.0,Rural,Y
773,Male,Yes,0.0,Not Graduate,No,7895,0.000000,143.00000,360.0,1.0,Rural,N
803,Male,Yes,2.0,Graduate,No,7874,3967.000000,336.00000,360.0,1.0,Rural,Y
929,Female,Yes,0.0,Graduate,No,7859,879.000000,165.00000,180.0,1.0,Semiurban,Y
831,Male,Yes,0.0,Graduate,No,7830,2183.000000,212.00000,360.0,1.0,Rural,Y
212,Male,Yes,1.0,Graduate,Yes,7787,0.000000,240.00000,360.0,1.0,Urban,Y
461,Male,Yes,4.0,Graduate,No,7740,0.000000,128.00000,180.0,1.0,Urban,Y
309,Male,Yes,2.0,Not Graduate,No,7667,0.000000,185.00000,360.0,0.0,Rural,Y
682,Male,Yes,0.0,Graduate,No,7666,0.000000,187.00000,360.0,1.0,Semiurban,Y
20,Male,Yes,0.0,Not Graduate,No,7660,0.000000,104.00000,360.0,0.0,Urban,N
969,Male,Yes,4.0,Graduate,No,7603,1213.000000,197.00000,360.0,1.0,Urban,Y
847,Female,No,1.0,Graduate,No,7600,0.000000,92.00000,360.0,1.0,Semiurban,Y
612,Male,Yes,2.0,Graduate,No,7583,0.000000,187.00000,360.0,1.0,Urban,Y
223,Male,Yes,0.0,Graduate,No,7578,1010.000000,175.00000,360.0,1.0,Semiurban,Y
920,Male,Yes,2.0,Graduate,Yes,7500,0.000000,183.00000,360.0,1.0,Rural,Y
741,Male,Yes,2.0,Graduate,No,7500,0.000000,225.00000,360.0,1.0,Urban,Y
641,Male,Yes,0.0,Graduate,No,7500,3750.000000,275.00000,360.0,1.0,Urban,Y
914,Male,Yes,1.0,Graduate,Yes,7500,0.000000,75.00000,360.0,1.0,Urban,Y
113,Female,No,1.0,Graduate,Yes,7451,0.000000,142.51153,360.0,1.0,Semiurban,Y
404,Female,No,0.0,Graduate,Yes,7441,0.000000,194.00000,360.0,1.0,Rural,N
650,Male,Yes,2.0,Graduate,No,7350,4029.000000,185.00000,180.0,1.0,Urban,Y
444,Male,Yes,0.0,Graduate,No,7333,8333.000000,175.00000,300.0,0.0,Rural,Y
107,Male,No,0.0,Not Graduate,No,7333,0.000000,120.00000,360.0,1.0,Rural,N
423,Male,Yes,1.0,Graduate,No,7250,1667.000000,110.00000,360.0,0.0,Urban,N
263,Female,No,0.0,Graduate,No,7200,0.000000,120.00000,360.0,1.0,Rural,Y
383,Male,No,0.0,Graduate,Yes,7167,0.000000,128.00000,360.0,1.0,Urban,Y
439,Female,Yes,0.0,Not Graduate,Yes,7142,0.000000,138.00000,360.0,1.0,Rural,Y
68,Male,Yes,4.0,Not Graduate,Yes,7100,0.000000,125.00000,60.0,1.0,Urban,Y
454,Male,No,0.0,Graduate,Yes,7085,0.000000,84.00000,360.0,1.0,Semiurban,Y
675,Male,Yes,0.0,Graduate,Yes,7016,292.000000,125.00000,360.0,1.0,Urban,Y
942,Male,Yes,4.0,Graduate,Yes,6958,1411.000000,150.00000,360.0,1.0,Rural,Y
142,Male,No,0.0,Graduate,Yes,6950,0.000000,175.00000,180.0,1.0,Semiurban,Y
296,Male,Yes,1.0,Graduate,No,6875,0.000000,200.00000,360.0,1.0,Semiurban,Y
958,Male,No,0.0,Graduate,No,6858,0.000000,176.00000,360.0,1.0,Rural,Y
713,Male,Yes,4.0,Graduate,No,6835,0.000000,188.00000,360.0,0.0,Semiurban,Y
922,Male,Yes,1.0,Graduate,No,6825,0.000000,162.00000,360.0,1.0,Rural,Y
364,Male,No,0.0,Graduate,Yes,6822,0.000000,141.00000,360.0,1.0,Rural,Y
756,Male,Yes,4.0,Not Graduate,No,6794,528.000000,139.00000,360.0,0.0,Urban,N
662,Male,No,0.0,Graduate,No,6792,3338.000000,187.00000,360.0,1.0,Urban,Y
529,Male,No,0.0,Not Graduate,No,6783,0.000000,130.00000,360.0,1.0,Semiurban,Y
95,Male,No,0.0,Graduate,No,6782,0.000000,142.51153,360.0,0.0,Urban,N
476,Male,Yes,2.0,Graduate,No,6700,1750.000000,230.00000,300.0,1.0,Semiurban,Y
550,Male,Yes,2.0,Graduate,Yes,6633,0.000000,142.51153,360.0,0.0,Rural,N
247,Male,Yes,1.0,Not Graduate,No,6608,0.000000,137.00000,180.0,1.0,Urban,Y
580,Male,Yes,2.0,Graduate,No,6540,0.000000,205.00000,360.0,1.0,Semiurban,Y
657,Male,No,0.0,Graduate,No,6500,2600.000000,200.00000,360.0,1.0,Semiurban,Y
890,Male,Yes,0.0,Graduate,No,6500,0.000000,144.00000,360.0,1.0,Urban,Y
740,Male,No,0.0,Graduate,No,6500,0.000000,71.00000,360.0,0.0,Urban,N
431,Male,No,0.0,Graduate,No,6500,0.000000,105.00000,360.0,0.0,Rural,N
910,Male,No,0.0,Graduate,No,6478,0.000000,108.00000,360.0,1.0,Semiurban,Y
539,Male,Yes,4.0,Graduate,No,6417,0.000000,157.00000,180.0,1.0,Rural,Y
574,Male,Yes,4.0,Graduate,No,6406,0.000000,150.00000,360.0,1.0,Semiurban,N
180,Male,Yes,1.0,Graduate,No,6400,7250.000000,180.00000,360.0,0.0,Urban,N
229,Male,No,0.0,Graduate,Yes,6400,0.000000,200.00000,360.0,1.0,Rural,Y
596,Male,Yes,2.0,Not Graduate,Yes,6383,1000.000000,187.00000,360.0,1.0,Rural,N
691,Male,No,0.0,Graduate,Yes,6356,0.000000,50.00000,360.0,1.0,Rural,Y
348,Male,Yes,0.0,Graduate,No,6333,4583.000000,259.00000,360.0,0.0,Semiurban,Y
368,Male,Yes,1.0,Graduate,No,6325,0.000000,175.00000,360.0,1.0,Semiurban,Y
915,Male,Yes,1.0,Graduate,No,6300,0.000000,125.00000,360.0,0.0,Urban,N
499,Male,No,0.0,Graduate,No,6283,4416.000000,209.00000,360.0,0.0,Rural,N
150,Male,No,0.0,Graduate,No,6277,0.000000,118.00000,360.0,0.0,Rural,N
709,Female,Yes,4.0,Graduate,No,6260,0.000000,110.00000,360.0,1.0,Semiurban,Y
411,Male,Yes,0.0,Graduate,No,6256,0.000000,160.00000,360.0,0.0,Urban,Y
227,Male,Yes,2.0,Graduate,No,6250,1695.000000,210.00000,360.0,1.0,Semiurban,Y
243,Male,Yes,2.0,Graduate,Yes,6250,1300.000000,108.00000,360.0,1.0,Rural,Y
224,Male,Yes,0.0,Graduate,No,6250,0.000000,128.00000,360.0,1.0,Semiurban,Y
645,Male,Yes,2.0,Graduate,No,6250,820.000000,192.00000,360.0,1.0,Urban,Y
91,Male,Yes,2.0,Graduate,No,6250,5654.000000,188.00000,180.0,1.0,Semiurban,Y
365,Male,No,0.0,Not Graduate,No,6216,0.000000,133.00000,360.0,1.0,Rural,N
851,Male,Yes,2.0,Not Graduate,No,6166,13983.000000,102.00000,360.0,1.0,Rural,Y
536,Male,Yes,0.0,Graduate,No,6133,3906.000000,324.00000,360.0,1.0,Urban,Y
573,Male,Yes,2.0,Not Graduate,No,6125,1625.000000,187.00000,480.0,1.0,Semiurban,N
412,Male,Yes,0.0,Not Graduate,No,6096,0.000000,218.00000,360.0,0.0,Rural,N
260,Male,Yes,1.0,Graduate,No,6083,4250.000000,330.00000,360.0,0.0,Urban,Y
129,Male,Yes,0.0,Graduate,No,6080,2569.000000,182.00000,360.0,0.0,Rural,N
511,Male,Yes,1.0,Graduate,No,6065,2004.000000,250.00000,360.0,1.0,Semiurban,Y
245,Male,No,0.0,Graduate,Yes,6050,4333.000000,120.00000,180.0,1.0,Urban,N
256,Male,No,0.0,Not Graduate,No,6045,0.000000,115.00000,360.0,0.0,Rural,N
192,Male,Yes,0.0,Not Graduate,No,6033,0.000000,160.00000,360.0,1.0,Urban,N
4,Male,No,0.0,Graduate,No,6000,0.000000,141.00000,360.0,1.0,Urban,Y
382,Female,No,0.0,Graduate,No,6000,0.000000,156.00000,360.0,1.0,Urban,Y
156,Male,Yes,1.0,Graduate,No,6000,0.000000,160.00000,360.0,0.0,Rural,Y
465,Male,No,0.0,Graduate,No,6000,0.000000,140.00000,360.0,1.0,Rural,Y
591,Male,Yes,2.0,Graduate,Yes,6000,0.000000,205.00000,240.0,1.0,Semiurban,N
83,Male,Yes,0.0,Graduate,No,6000,2250.000000,265.00000,360.0,0.0,Semiurban,N
21,Male,Yes,1.0,Graduate,No,5955,5625.000000,315.00000,360.0,1.0,Urban,Y
381,Male,No,0.0,Graduate,No,5941,4232.000000,296.00000,360.0,1.0,Semiurban,Y
427,Male,Yes,2.0,Graduate,No,5935,0.000000,133.00000,360.0,1.0,Semiurban,Y
562,Male,Yes,0.0,Graduate,No,5923,2054.000000,211.00000,360.0,1.0,Rural,Y
763,Male,No,0.0,Graduate,No,5900,0.000000,150.00000,360.0,1.0,Urban,Y
0,Male,No,0.0,Graduate,No,5849,0.000000,142.51153,360.0,1.0,Urban,Y
652,Male,No,0.0,Graduate,Yes,5833,0.000000,116.00000,360.0,1.0,Urban,Y
809,Male,No,0.0,Graduate,Yes,5833,0.000000,116.00000,360.0,1.0,Urban,Y
882,Male,Yes,2.0,Graduate,No,5833,750.000000,49.00000,360.0,0.0,Rural,N
420,Male,Yes,0.0,Graduate,No,5829,0.000000,138.00000,360.0,1.0,Rural,Y
772,Male,No,1.0,Graduate,No,5823,2529.000000,187.00000,360.0,1.0,Semiurban,Y
47,Male,Yes,0.0,Graduate,No,5821,0.000000,144.00000,360.0,1.0,Urban,Y
240,Male,Yes,2.0,Graduate,No,5819,5000.000000,120.00000,360.0,1.0,Rural,Y
327,Male,Yes,0.0,Graduate,Yes,5818,2160.000000,184.00000,360.0,1.0,Semiurban,Y
966,Male,Yes,0.0,Graduate,No,5817,910.000000,109.00000,360.0,1.0,Urban,Y
514,Male,No,0.0,Graduate,No,5815,3666.000000,311.00000,360.0,1.0,Rural,N
563,Male,No,0.0,Not Graduate,Yes,5800,0.000000,132.00000,360.0,1.0,Semiurban,Y
599,Male,Yes,2.0,Graduate,No,5780,0.000000,192.00000,360.0,1.0,Urban,Y
891,Female,No,0.0,Graduate,No,5769,0.000000,110.00000,180.0,1.0,Semiurban,Y
313,Male,Yes,2.0,Graduate,Yes,5746,0.000000,144.00000,84.0,0.0,Rural,Y
236,Male,Yes,0.0,Graduate,No,5746,0.000000,255.00000,360.0,0.0,Urban,N
65,Male,Yes,0.0,Graduate,No,5726,4595.000000,258.00000,360.0,1.0,Semiurban,N
614,Male,Yes,0.0,Graduate,No,5720,0.000000,110.00000,360.0,1.0,Urban,Y
827,Male,No,0.0,Graduate,No,5708,0.000000,150.00000,360.0,1.0,Rural,Y
173,Male,Yes,0.0,Graduate,No,5708,5625.000000,187.00000,360.0,1.0,Semiurban,Y
213,Male,Yes,4.0,Not Graduate,Yes,5703,0.000000,130.00000,360.0,1.0,Rural,Y
602,Male,Yes,4.0,Graduate,No,5703,0.000000,128.00000,360.0,1.0,Urban,Y
89,Male,Yes,0.0,Graduate,No,5695,4167.000000,175.00000,360.0,1.0,Semiurban,Y
522,Male,Yes,4.0,Graduate,Yes,5677,1424.000000,100.00000,360.0,1.0,Rural,Y
120,Male,Yes,2.0,Graduate,No,5667,2667.000000,180.00000,360.0,1.0,Rural,Y
629,Male,No,1.0,Graduate,No,5667,0.000000,131.00000,360.0,1.0,Urban,Y
887,Male,Yes,2.0,Graduate,No,5667,440.000000,130.00000,360.0,0.0,Semiurban,N
46,Male,Yes,1.0,Graduate,No,5649,0.000000,44.00000,360.0,1.0,Urban,Y
654,Male,Yes,0.0,Graduate,No,5629,818.000000,100.00000,360.0,1.0,Urban,Y
776,Male,No,0.0,Graduate,No,5583,0.000000,116.00000,360.0,1.0,Urban,Y
118,Male,Yes,0.0,Graduate,No,5568,2142.000000,175.00000,360.0,1.0,Rural,N
474,Male,No,2.0,Graduate,No,5532,4648.000000,162.00000,360.0,1.0,Rural,Y
896,Female,No,0.0,Graduate,No,5530,0.000000,135.00000,360.0,0.0,Urban,Y
177,Male,Yes,4.0,Graduate,No,5516,11300.000000,495.00000,360.0,0.0,Semiurban,N
944,Male,Yes,0.0,Graduate,No,5509,0.000000,143.00000,360.0,1.0,Rural,Y
335,Male,Yes,2.0,Graduate,Yes,5503,4490.000000,70.00000,360.0,1.0,Semiurban,Y
235,Male,Yes,1.0,Graduate,No,5500,1260.000000,170.00000,360.0,1.0,Rural,Y
353,Female,Yes,0.0,Graduate,Yes,5500,0.000000,105.00000,360.0,0.0,Rural,N
389,Male,Yes,0.0,Graduate,No,5488,0.000000,125.00000,360.0,1.0,Rural,Y
555,Male,Yes,1.0,Graduate,No,5468,1032.000000,26.00000,360.0,1.0,Semiurban,Y
293,Female,No,2.0,Graduate,No,5417,0.000000,143.00000,480.0,0.0,Urban,N
141,Male,No,0.0,Graduate,No,5417,0.000000,168.00000,360.0,1.0,Urban,Y
5,Male,Yes,2.0,Graduate,Yes,5417,4196.000000,267.00000,360.0,1.0,Urban,Y
638,Male,Yes,0.0,Graduate,No,5400,4380.000000,290.00000,360.0,1.0,Urban,Y
379,Male,Yes,2.0,Graduate,No,5391,0.000000,130.00000,360.0,1.0,Urban,Y
826,Male,Yes,4.0,Graduate,Yes,5384,0.000000,150.00000,360.0,1.0,Semiurban,Y
938,Male,Yes,0.0,Graduate,No,5333,0.000000,90.00000,360.0,1.0,Rural,Y
491,Male,Yes,1.0,Not Graduate,No,5333,1131.000000,186.00000,360.0,0.0,Urban,Y
825,Male,No,0.0,Graduate,No,5333,2400.000000,200.00000,360.0,0.0,Rural,N
968,Male,Yes,4.0,Not Graduate,No,5316,187.000000,158.00000,180.0,0.0,Semiurban,Y
110,Male,No,0.0,Graduate,No,5316,0.000000,136.00000,360.0,1.0,Urban,Y
924,Male,No,0.0,Graduate,No,5314,0.000000,147.00000,360.0,1.0,Urban,Y
668,Male,Yes,0.0,Not Graduate,Yes,5293,0.000000,92.00000,360.0,1.0,Urban,Y
527,Male,Yes,1.0,Not Graduate,No,5285,1430.000000,161.00000,360.0,0.0,Semiurban,Y
74,Male,Yes,4.0,Graduate,Yes,5266,1774.000000,187.00000,360.0,1.0,Semiurban,Y
257,Male,Yes,4.0,Graduate,No,5250,0.000000,94.00000,360.0,1.0,Urban,N

In [11]:
cred.Gender = cred.Gender.fillna("Male")
cred.Married = cred.Married.fillna("Yes")
cred.Dependents = cred.Dependents.fillna(2)
cred.Self_Employed = cred.Self_Employed.fillna("No")
cred.LoanAmount = cred.LoanAmount.fillna(cred.LoanAmount.mean())
cred.Loan_Amount_Term = cred.Loan_Amount_Term.fillna(360)
cred.Credit_History = cred.Credit_History.fillna(0)

In [13]:
cred = cred.drop(['Loan_ID'] , axis =1)

In [16]:
cred1 = pd.get_dummies(cred)

In [17]:
cred1.shape

(981, 19)

In [18]:
cred1.head()

,Dependents,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Gender_Female,Gender_Male,Married_No,Married_Yes,Education_Graduate,Education_Not Graduate,Self_Employed_No,Self_Employed_Yes,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban,Loan_Status_N,Loan_Status_Y
0,0.0,5849,0.0,142.51153,360.0,1.0,0,1,1,0,1,0,1,0,0,0,1,0,1
1,1.0,4583,1508.0,128.00000,360.0,1.0,0,1,0,1,1,0,1,0,1,0,0,1,0
2,0.0,3000,0.0,66.00000,360.0,1.0,0,1,0,1,1,0,0,1,0,0,1,0,1
3,0.0,2583,2358.0,120.00000,360.0,1.0,0,1,0,1,0,1,1,0,0,0,1,0,1
4,0.0,6000,0.0,141.00000,360.0,1.0,0,1,1,0,1,0,1,0,0,0,1,0,1

In [39]:
cred = cred.rename({'ApplicantIncome' : 'Applicant_Income'}, axis = 1) #based on column name

In [33]:
cred = cred.rename(columns = {cred.columns[1] : 'Gender1'}) # based on column position

In [40]:
cred.head()

,Loan_ID,Gender1,Married,Dependents,Education,Self_Employed,Applicant-Income,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [25]:
cred = cred.drop(['Gender1'] , axis = 1)

In [51]:
twice_income = 2 * cred.ApplicantIncome

In [67]:
cred2 = pd.concat([cred , twice_income] , axis =1)

In [75]:
cred2.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,New_Applicant_Income
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y,11698
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N,9166
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y,6000
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y,5166
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y,12000

In [65]:
cred2 = cred2.rename(columns = {cred.columns[-1] : 'New_Applicant_Income'})

In [64]:
cred2.shape

(981, 14)

In [69]:
names = list(cred2.columns)

In [73]:
names

['Loan_ID',
 'Gender',
 'Married',
 'Dependents',
 'Education',
 'Self_Employed',
 'ApplicantIncome',
 'CoapplicantIncome',
 'LoanAmount',
 'Loan_Amount_Term',
 'Credit_History',
 'Property_Area',
 'Loan_Status',
 'New_Applicant_Income']

In [72]:
names[13] = 'New_Applicant_Income'

In [74]:
cred2.columns = names

In [76]:
cred1['New_Applicant_Income'] = twice_income

In [77]:
cred1.head()

,Dependents,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Gender_Female,Gender_Male,Married_No,Married_Yes,Education_Graduate,Education_Not Graduate,Self_Employed_No,Self_Employed_Yes,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban,Loan_Status_N,Loan_Status_Y,New_Applicant_Income
0,0.0,5849,0.0,142.51153,360.0,1.0,0,1,1,0,1,0,1,0,0,0,1,0,1,11698
1,1.0,4583,1508.0,128.00000,360.0,1.0,0,1,0,1,1,0,1,0,1,0,0,1,0,9166
2,0.0,3000,0.0,66.00000,360.0,1.0,0,1,0,1,1,0,0,1,0,0,1,0,1,6000
3,0.0,2583,2358.0,120.00000,360.0,1.0,0,1,0,1,0,1,1,0,0,0,1,0,1,5166
4,0.0,6000,0.0,141.00000,360.0,1.0,0,1,1,0,1,0,1,0,0,0,1,0,1,12000

In [18]:
ctg = pd.read_csv(r"D:Downloads/Datasets/CTG.csv")

In [79]:
ctg.shape

(2126, 4)

In [80]:
ctg1 = ctg.drop_duplicates()

In [81]:
ctg1.shape

(1030, 4)

In [ ]:
#Co-relation

In [19]:
lcn = pd.read_csv(r"D:Downloads/Datasets/LungCapData.csv")

In [83]:
lcn.shape

(725, 6)

In [86]:
lcn.describe()

          LungCap         Age      Height
count  725.000000  725.000000  725.000000
mean     7.863148   12.326897   64.836276
std      2.662008    4.004750    7.202144
min      0.507000    3.000000   45.300000
25%      6.150000    9.000000   59.900000
50%      8.000000   13.000000   65.400000
75%      9.800000   15.000000   70.300000
max     14.675000   19.000000   81.800000

In [88]:
lcn.isnull().sum()

LungCap      0
Age          0
Height       0
Smoke        0
Gender       0
Caesarean    0
dtype: int64

In [89]:
lcn.corr()

          LungCap       Age    Height
LungCap  1.000000  0.819675  0.912187
Age      0.819675  1.000000  0.835737
Height   0.912187  0.835737  1.000000